services:
  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    ulimits:
      memlock: -1
    command: ["--proactor_threads=2", "--maxmemory=512mb"]

  rustfs:
    container_name: rustfs
    image: docker.io/rustfs/rustfs:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUSTFS_ROOT_USER: ${RUSTFS_ROOT_USER}
      RUSTFS_ROOT_PASSWORD: ${RUSTFS_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - jevek_fs:/data

  nats:
    image: docker.io/nats:2.11-alpine
    container_name: nats
    restart: unless-stopped
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"
      - "--http_port=8222"
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    volumes:
      - nats_data:/data/jetstream
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://127.0.0.1:8222/healthz || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  jevek_fs:
  dragonfly_data:
  nats_data:
    driver: local
