version: "3.9"

services:
    postgres:
        container_name: postgres
        image: docker.io/postgis/postgis:16-3.4
        restart: unless-stopped
        environment:
            POSTGRES_USER: wedi
            POSTGRES_PASSWORD: wedime
            POSTGRES_DB: twaso
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d twaso -U wedi"]
            interval: 10s
            timeout: 5s
            retries: 5

        pgadmin:
            container_name: pgadmin
            image: docker.io/dpage/pgadmin4
            restart: unless-stopped
            environment:
                PGADMIN_DEFAULT_EMAIL: wedi@pgadmin.com
                PGADMIN_DEFAULT_PASSWORD: wedime
            ports:
                - "5040:80"
            volumes:
                - pgadmin_data:/var/lib/pgadmin
            depends_on:
                postgres:
                    condition: service_healthy
            healthcheck:
                test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
                interval: 30s
                timeout: 10s
                retries: 3

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local
