//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AccLimitType;
use super::sea_orm_active_enums::AccLimitUnit;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "account_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "unique_acc_limit_acc_id_limit_type")]
    pub account_id: i64,
    #[sea_orm(unique_key = "unique_acc_limit_acc_id_limit_type")]
    pub limit_type: AccLimitType,
    pub limit_unit: AccLimitUnit,
    pub limit_value: i64,
    pub current_value: i64,
    pub last_reset_at: Option<DateTimeWithTimeZone>,
    pub is_active: Option<bool>,
    pub effective_from: DateTimeWithTimeZone,
    pub effective_to: DateTimeWithTimeZone,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
