//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccTypeStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub account_type_id: i64,
    #[sea_orm(unique)]
    pub account_number: Option<String>,
    pub account_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub current_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub available_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub ledger_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub hold_balance: Option<Decimal>,
    pub status: Option<AccTypeStatus>,
    pub activation_date: Option<DateTimeWithTimeZone>,
    pub dormancy_date: Option<DateTimeWithTimeZone>,
    pub frozen_at: Option<DateTimeWithTimeZone>,
    pub frozen_reason: Option<String>,
    pub is_overdraft_allowable: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub overdraft_limit: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub overdraft_used: Option<Decimal>,
    pub parent_account_id: Option<i64>,
    pub tags: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub closure_reason: Option<String>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub frozen_by: Option<i64>,
    pub created_by: Option<i64>,
    pub closed_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_balances::Entity")]
    AccountBalances,
    #[sea_orm(has_many = "super::account_limits::Entity")]
    AccountLimits,
    #[sea_orm(
        belongs_to = "super::account_types::Entity",
        from = "Column::AccountTypeId",
        to = "super::account_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccountTypes,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentAccountId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::aml_alerts::Entity")]
    AmlAlerts,
    #[sea_orm(has_many = "super::cards::Entity")]
    Cards,
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(has_many = "super::fee_applications::Entity")]
    FeeApplications,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::loan_repayments::Entity")]
    LoanRepayments,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(has_many = "super::refund_workflows::Entity")]
    RefundWorkflows,
    #[sea_orm(has_many = "super::saving_goals::Entity")]
    SavingGoals,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ClosedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff3,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::FrozenBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(has_many = "super::staff_tasks::Entity")]
    StaffTasks,
    #[sea_orm(has_many = "super::suspicious_transaction_reports::Entity")]
    SuspiciousTransactionReports,
}

impl Related<super::account_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountBalances.def()
    }
}

impl Related<super::account_limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountLimits.def()
    }
}

impl Related<super::account_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountTypes.def()
    }
}

impl Related<super::aml_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlAlerts.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::fee_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeApplications.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_repayments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRepayments.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::refund_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundWorkflows.def()
    }
}

impl Related<super::saving_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingGoals.def()
    }
}

impl Related<super::staff_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTasks.def()
    }
}

impl Related<super::suspicious_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuspiciousTransactionReports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
