//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account_balances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    #[sea_orm(unique)]
    pub balance_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub opening_balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_credits: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_debits: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub closing_balance: Decimal,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
