//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccTypeIntCalc;
use super::sea_orm_active_enums::AccTypeIntPayoutFreq;
use super::sea_orm_active_enums::AccTypeStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub category_id: i64,
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub minimum_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub maximum_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub interest_rate: Option<Decimal>,
    pub interest_rate_calc_method: Option<AccTypeIntCalc>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub kyc_tier: Option<Json>,
    pub interest_payout_frequency: Option<AccTypeIntPayoutFreq>,
    pub is_overdraft_allowable: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub overdraft_limit: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub overdraft_interest_rate: Option<Decimal>,
    pub dormancy_period_days: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub maintenance_fee: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub withdrawal_fee: Option<Decimal>,
    pub status: Option<AccTypeStatus>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
