//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccrualReferenceType;
use super::sea_orm_active_enums::AccrualStatus;
use super::sea_orm_active_enums::AccrualType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "accruals_and_provisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub accrual_type: AccrualType,
    pub account_id: i64,
    pub accrual_date: Date,
    pub posting_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub accrual_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub reversal_amount: Option<Decimal>,
    pub reference_type: Option<AccrualReferenceType>,
    pub reference_id: Option<i64>,
    pub status: Option<AccrualStatus>,
    pub posted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::AccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
