//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_audit_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub admin_id: i64,
    pub institution_id: Option<i64>,
    pub action: String,
    pub resource_type: Option<String>,
    pub resource_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub old_values: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub new_values: Option<Json>,
    #[sea_orm(column_type = "custom(\"inet\")", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::super_admins::Entity",
        from = "Column::AdminId",
        to = "super::super_admins::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SuperAdmins,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::super_admins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuperAdmins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
