//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AgentEntityType;
use super::sea_orm_active_enums::AgentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub branch_id: i64,
    #[sea_orm(unique)]
    pub agent_number: String,
    pub agent_name: Option<String>,
    pub business_name: Option<String>,
    pub entity_type: Option<AgentEntityType>,
    pub business_registration_number: Option<String>,
    pub phone_country_code: Option<String>,
    pub phone_number: Option<String>,
    pub email: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub operating_address: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub business_address: Option<Json>,
    pub kyc_completed_at: Option<DateTimeWithTimeZone>,
    pub settlement_account_id: Option<i64>,
    pub commission_account_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub transaction_volume_today: Option<Decimal>,
    pub transaction_count_today: Option<i32>,
    pub last_transaction_at: Option<DateTimeWithTimeZone>,
    pub status: Option<AgentStatus>,
    pub suspension_reason: Option<String>,
    pub terminated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub geofence_radius: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub kyc_status: Option<Json>,
    pub verified_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::CommissionAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::SettlementAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts1,
    #[sea_orm(has_many = "super::agent_audits::Entity")]
    AgentAudits,
    #[sea_orm(has_many = "super::agent_commissions::Entity")]
    AgentCommissions,
    #[sea_orm(has_many = "super::agent_performance::Entity")]
    AgentPerformance,
    #[sea_orm(has_many = "super::agent_settlements::Entity")]
    AgentSettlements,
    #[sea_orm(has_many = "super::agent_transactions::Entity")]
    AgentTransactions,
    #[sea_orm(has_many = "super::agent_wallets::Entity")]
    AgentWallets,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Branches,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::notification_queue::Entity")]
    NotificationQueue,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::VerifiedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::agent_audits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentAudits.def()
    }
}

impl Related<super::agent_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissions.def()
    }
}

impl Related<super::agent_performance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentPerformance.def()
    }
}

impl Related<super::agent_settlements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentSettlements.def()
    }
}

impl Related<super::agent_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentTransactions.def()
    }
}

impl Related<super::agent_wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentWallets.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::notification_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationQueue.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
