//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AgentCommissionRuleCommType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_commission_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub rule_name: String,
    pub rule_description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_transaction_types: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_agents: Option<Json>,
    pub commission_type: Option<AgentCommissionRuleCommType>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub commission_value: Option<Decimal>,
    pub has_slabs: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub slab_config: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub min_commission: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub max_commission: Option<Decimal>,
    pub is_active: Option<bool>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_commissions::Entity")]
    AgentCommissions,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(has_many = "super::staff_commissions::Entity")]
    StaffCommissions,
}

impl Related<super::agent_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissions.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffCommissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
