//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_performance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub agent_id: i64,
    pub report_date: Date,
    pub deposit_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub deposit_amount: Option<Decimal>,
    pub withdrawal_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub withdrawal_amount: Option<Decimal>,
    pub loan_repayment_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub loan_repayment_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub commission_earned: Option<Decimal>,
    pub active_customer_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub performance_score: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
