//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AgentTransStatus;
use super::sea_orm_active_enums::AgentTransType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub agent_id: i64,
    pub agent_wallet_id: i64,
    pub transaction_id: Option<i64>,
    pub transaction_type: AgentTransType,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub commission_earned: Option<Decimal>,
    pub customer_phone: Option<String>,
    pub customer_account: Option<String>,
    pub status: Option<AgentTransStatus>,
    pub posted_at: Option<DateTimeWithTimeZone>,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub transaction_address: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub geo_accuracy: Option<Decimal>,
    pub reconciled_at: Option<DateTimeWithTimeZone>,
    pub is_reconciled: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agent_wallets::Entity",
        from = "Column::AgentWalletId",
        to = "super::agent_wallets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AgentWallets,
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::agent_wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentWallets.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
