//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AgentKycDocsDoctype;
use super::sea_orm_active_enums::VerificationStatusType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_kyc_docs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub agent_id: i64,
    pub document_type: Option<AgentKycDocsDoctype>,
    pub document_url: Option<String>,
    pub verification_status: Option<VerificationStatusType>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub rejection_reason: Option<String>,
    pub verified_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::VerifiedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
