//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AmlCaseStatus;
use super::sea_orm_active_enums::AmlCasesPriority;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aml_cases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub case_number: String,
    pub title: String,
    pub description: Option<String>,
    pub priority: AmlCasesPriority,
    pub status: AmlCaseStatus,
    pub assigned_investigator: Option<i64>,
    pub resolution: Option<String>,
    pub resolved_by: Option<i64>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::aml_actions::Entity")]
    AmlActions,
    #[sea_orm(has_many = "super::aml_case_notes::Entity")]
    AmlCaseNotes,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedInvestigator",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ResolvedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::aml_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlActions.def()
    }
}

impl Related<super::aml_case_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlCaseNotes.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
