//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AmlEntityType;
use super::sea_orm_active_enums::AmlRiskLevelEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aml_blacklists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub entity_type: Option<AmlEntityType>,
    pub entity_id: Option<i64>,
    pub reason: Option<String>,
    pub severity: Option<AmlRiskLevelEnum>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
