//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aml_case_notes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub case_id: i64,
    pub investigator_id: i64,
    pub note: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aml_cases::Entity",
        from = "Column::CaseId",
        to = "super::aml_cases::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AmlCases,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::InvestigatorId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::aml_cases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlCases.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
