//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AmlRuleActions;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aml_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub case_id: i64,
    pub alert_id: i64,
    pub action_type: Option<AmlRuleActions>,
    pub performedby: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aml_alerts::Entity",
        from = "Column::AlertId",
        to = "super::aml_alerts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AmlAlerts,
    #[sea_orm(
        belongs_to = "super::aml_cases::Entity",
        from = "Column::CaseId",
        to = "super::aml_cases::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AmlCases,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::Performedby",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::aml_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlAlerts.def()
    }
}

impl Related<super::aml_cases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlCases.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
