//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AuditTrailsAction;
use super::sea_orm_active_enums::AuditTrailsResourceType;
use super::sea_orm_active_enums::AuditTrailsUserType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_trails")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub event_type: String,
    pub event_description: Option<String>,
    pub event_timestamp: Option<DateTimeWithTimeZone>,
    pub user_id: Option<i64>,
    pub user_type: Option<AuditTrailsUserType>,
    pub session_id: Option<String>,
    #[sea_orm(column_type = "custom(\"inet\")", nullable)]
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub resource_type: Option<AuditTrailsResourceType>,
    pub resource_id: Option<i64>,
    pub action: AuditTrailsAction,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub old_values: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub new_values: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub changes: Option<Json>,
    pub maker_checker_workflow_id: Option<i64>,
    pub is_success: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub tags: Option<Vec<String>>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
