//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "branches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub code: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub address: Option<Json>,
    pub phone: Option<String>,
    pub email: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub location: Option<Json>,
    pub is_main: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub cash_limit: Option<Decimal>,
    pub is_active: Option<bool>,
    pub status: Option<String>,
    pub is_deleted: Option<bool>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub manager_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agents::Entity")]
    Agents,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ManagerId",
        to = "super::staff::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Staff,
    #[sea_orm(has_many = "super::tellers::Entity")]
    Tellers,
    #[sea_orm(has_many = "super::vaults::Entity")]
    Vaults,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::tellers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tellers.def()
    }
}

impl Related<super::vaults::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vaults.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
