//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::CardLimitReset;
use super::sea_orm_active_enums::CardLimitType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "card_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique_key = "unique_card_lim_card_lim_type")]
    pub card_id: i64,
    #[sea_orm(unique_key = "unique_card_lim_card_lim_type")]
    pub limit_type: Option<CardLimitType>,
    pub limit_amount: Option<i64>,
    pub current_usage: Option<i64>,
    pub reset_freq: Option<CardLimitReset>,
    pub last_reset_at: Option<DateTimeWithTimeZone>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cards::Entity",
        from = "Column::CardId",
        to = "super::cards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cards,
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
