//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CardBrand;
use super::sea_orm_active_enums::CardForm;
use super::sea_orm_active_enums::CardStatus;
use super::sea_orm_active_enums::CardType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub account_id: i64,
    pub card_number_hashed: String,
    pub card_number_masked: String,
    pub card_form_factor: Option<CardForm>,
    pub card_type: Option<CardType>,
    pub card_brand: Option<CardBrand>,
    pub card_bin: Option<String>,
    pub last_four: Option<String>,
    pub expiry_month: Option<i32>,
    pub expiry_year: Option<i32>,
    pub cvv_hash: Option<String>,
    pub pin_hash: Option<String>,
    pub pin_retries: Option<i32>,
    pub pin_blocked_at: Option<DateTimeWithTimeZone>,
    pub card_status: Option<CardStatus>,
    pub activation_date: Option<DateTimeWithTimeZone>,
    pub blocking_reason: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub daily_atm_limit: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub daily_pos_limit: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub daily_online_limit: Option<Decimal>,
    pub cardholder_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub delivery_address: Option<Json>,
    pub delivery_status: Option<String>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub card_provider: Option<String>,
    pub card_provider_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::card_limits::Entity")]
    CardLimits,
    #[sea_orm(has_many = "super::card_transactions::Entity")]
    CardTransactions,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::card_limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardLimits.def()
    }
}

impl Related<super::card_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardTransactions.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
