//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CardTransactionsStatus;
use super::sea_orm_active_enums::CardTransactionsTransChannel;
use super::sea_orm_active_enums::CardTransactionsTransType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "card_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub card_id: i64,
    #[sea_orm(unique)]
    pub transaction_reference: Option<String>,
    pub external_reference: Option<String>,
    pub merchant_name: Option<String>,
    pub merchant_category_code: Option<String>,
    pub merchant_id: Option<String>,
    pub transaction_type: CardTransactionsTransType,
    pub transaction_channel: Option<CardTransactionsTransChannel>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub billing_amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub billing_currency: Option<Json>,
    pub transaction_date: Option<DateTimeWithTimeZone>,
    pub settlement_date: Option<Date>,
    pub status: Option<CardTransactionsStatus>,
    pub response_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response_message: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub atm_location: Option<Json>,
    pub pos_terminal_id: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::card_disputes::Entity")]
    CardDisputes,
    #[sea_orm(
        belongs_to = "super::cards::Entity",
        from = "Column::CardId",
        to = "super::cards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cards,
    #[sea_orm(has_many = "super::chargebacks::Entity")]
    Chargebacks,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::card_disputes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardDisputes.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl Related<super::chargebacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chargebacks.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
