//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CardDisputeStatus;
use super::sea_orm_active_enums::CardDisputeType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "card_disputes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub card_transaction_id: i64,
    pub dispute_type: CardDisputeType,
    pub dispute_reason: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub amount_disputed: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub provisional_credit_amount: Option<Decimal>,
    pub status: Option<CardDisputeStatus>,
    pub is_chargeback_initiated: Option<bool>,
    pub chargeback_date: Option<Date>,
    pub resolution: Option<String>,
    pub final_decision: Option<String>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub assigned_to: Option<i64>,
    pub resolved_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::card_transactions::Entity",
        from = "Column::CardTransactionId",
        to = "super::card_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CardTransactions,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedTo",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ResolvedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::card_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardTransactions.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
