//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ChargebackStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chargebacks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_id: i64,
    pub card_transaction_id: Option<i64>,
    pub dispute_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub chargeback_amount: Decimal,
    pub chargeback_reason_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub chargeback_reason: Option<String>,
    pub status: Option<ChargebackStatus>,
    pub initiated_at: Option<DateTimeWithTimeZone>,
    pub representment_due_date: Option<Date>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub provisional_credit_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub final_liability_amount: Option<Decimal>,
    pub network_reference: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub network_response: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::card_transactions::Entity",
        from = "Column::CardTransactionId",
        to = "super::card_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CardTransactions,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::card_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardTransactions.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
