//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chart_of_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    #[sea_orm(unique)]
    pub account_code: Option<String>,
    pub account_name: Option<String>,
    pub account_type: Option<String>,
    pub parent_account_id: Option<i64>,
    pub is_active: Option<bool>,
    pub is_system_account: Option<bool>,
    pub currency_code: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accruals_and_provisions::Entity")]
    AccrualsAndProvisions,
    #[sea_orm(has_many = "super::commission_payouts::Entity")]
    CommissionPayouts,
    #[sea_orm(has_many = "super::gl_daily_balances::Entity")]
    GlDailyBalances,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::savings_products::Entity")]
    SavingsProducts,
}

impl Related<super::accruals_and_provisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccrualsAndProvisions.def()
    }
}

impl Related<super::commission_payouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionPayouts.def()
    }
}

impl Related<super::gl_daily_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlDailyBalances.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::savings_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsProducts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
