//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ContributionStatus;
use super::sea_orm_active_enums::ContributionType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contributions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub saving_goal_id: Option<i64>,
    pub customer_id: i64,
    pub contribution_cycle_id: Option<i64>,
    pub account_id: Option<i64>,
    pub transaction_id: Option<i64>,
    pub contribution_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub amount: Decimal,
    pub contribution_type: Option<ContributionType>,
    pub contribution_reference: Option<String>,
    pub is_missed_contribution: Option<bool>,
    pub missed_contribution_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub penalty_applied: Option<Decimal>,
    pub status: Option<ContributionStatus>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::contribution_cycles::Entity",
        from = "Column::ContributionCycleId",
        to = "super::contribution_cycles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContributionCycles,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::saving_goals::Entity",
        from = "Column::SavingGoalId",
        to = "super::saving_goals::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SavingGoals,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::contribution_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContributionCycles.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::saving_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingGoals.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
