//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub slug: String,
    pub name: String,
    pub official_name: Option<String>,
    pub capital_city: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    pub flag_url: Option<String>,
    pub call_code: String,
    pub iso_code: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub more_data: Option<Json>,
    pub is_active: bool,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::customer_identifications::Entity")]
    CustomerIdentifications,
    #[sea_orm(has_many = "super::customers::Entity")]
    Customers,
    #[sea_orm(has_many = "super::institutions::Entity")]
    Institutions,
}

impl Related<super::customer_identifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerIdentifications.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
