//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "credit_bureau_reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_id: i64,
    pub customer_id: i64,
    pub inquiry_type: String,
    pub loan_application_id: Option<i64>,
    pub bureau_customer_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub report_data: Option<Json>,
    pub credit_score: Option<i32>,
    pub risk_grade: Option<String>,
    pub number_of_inquiries: Option<i32>,
    pub inquiries_last30_days: Option<i32>,
    pub total_accounts: Option<i32>,
    pub active_accounts: Option<i32>,
    pub defaults_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_outstanding_default_amount: Option<Decimal>,
    pub status: Option<String>,
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub consent_provided: Option<bool>,
    pub consent_date: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::integration_providers::Entity",
        from = "Column::ProviderId",
        to = "super::integration_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IntegrationProviders,
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LoanApplications,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
