//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "currencies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    #[sea_orm(unique)]
    pub code: String,
    #[sea_orm(unique)]
    pub numeric_code: Option<String>,
    pub name: String,
    pub symbol: Option<String>,
    pub native_symbol: Option<String>,
    pub decimal_places: i16,
    pub rounding_mode: Option<String>,
    pub is_fiat: bool,
    pub is_crypto: bool,
    pub crypto_type: Option<String>,
    pub contract_address: Option<String>,
    pub blockchain_network: Option<String>,
    pub is_active: bool,
    pub is_tradeable: bool,
    pub is_withdrawable: bool,
    pub is_depositable: bool,
    pub min_transfer_amount: Option<i64>,
    pub max_transfer_amount: Option<i64>,
    pub transfer_fee_fixed: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))", nullable)]
    pub transfer_fee_percent: Option<Decimal>,
    pub daily_transfer_limit: Option<i64>,
    pub country_code: Option<String>,
    pub region: Option<String>,
    pub central_bank: Option<String>,
    pub issuing_authority: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub color_hex: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub sort_order: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deactivated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deactivated_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
