//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CustomerSessionsStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customer_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub device_id: Option<String>,
    pub device_type: Option<String>,
    pub device_os: Option<String>,
    pub device_fingerprint: Option<String>,
    pub session_token_hash: String,
    pub refresh_token_hash: Option<String>,
    pub mfa_verified: Option<bool>,
    pub mfa_method: Option<String>,
    #[sea_orm(column_type = "custom(\"inet\")", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub location: Option<Json>,
    pub session_status: Option<CustomerSessionsStatus>,
    pub is_current: Option<bool>,
    pub login_at: Option<DateTimeWithTimeZone>,
    pub last_activity_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub logged_out_at: Option<DateTimeWithTimeZone>,
    pub login_method: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
