//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customer_app_preferences")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub language_code: Option<String>,
    pub currency_code: Option<String>,
    pub timezone: Option<String>,
    pub biometric_enabled: Option<bool>,
    pub pin_enabled: Option<bool>,
    pub quick_access_enabled: Option<bool>,
    pub push_notifications_enabled: Option<bool>,
    pub marketing_notifications_enabled: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub dashboard_layout: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub favorite_accounts: Option<Json>,
    pub data_sharing_consent: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub consents: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
