//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::VerificationStatusType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customer_identifications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub customer_id: i64,
    pub id_type: Option<String>,
    pub id_number: Option<String>,
    pub issuing_country_id: i64,
    pub issue_date: Option<Date>,
    pub expiry_date: Option<Date>,
    pub front_image_url: Option<String>,
    pub back_image_url: Option<String>,
    pub selfie_image_url: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))", nullable)]
    pub face_match_score: Option<Decimal>,
    pub face_match_passed: Option<bool>,
    pub verification_status: Option<VerificationStatusType>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub rejection_reason: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub verified_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::IssuingCountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Countries,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(has_many = "super::kyc_provider_checks::Entity")]
    KycProviderChecks,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::VerifiedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::kyc_provider_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KycProviderChecks.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
