//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CustomerType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_type: Option<CustomerType>,
    #[sea_orm(unique)]
    pub customer_number: Option<String>,
    pub risk_level: Option<String>,
    pub status: Option<String>,
    pub is_black_listed: Option<bool>,
    pub black_list_reason: Option<String>,
    pub first_name: Option<String>,
    pub middle_name: Option<String>,
    pub last_name: Option<String>,
    pub date_of_birth: Option<Date>,
    pub gender: Option<String>,
    pub nationality: Option<String>,
    pub phone_country_code: Option<String>,
    pub phone_number: Option<String>,
    pub email: Option<String>,
    pub is_phone_verified: Option<bool>,
    pub is_email_verified: Option<bool>,
    pub phone_verified_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub residential_address: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub postal_address: Option<Json>,
    pub city: Option<String>,
    pub state_province: Option<String>,
    pub country_id: Option<i64>,
    pub occupation: Option<String>,
    pub employer_name: Option<String>,
    pub income_source: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub monthly_income: Option<Decimal>,
    pub employee_number: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub next_of_kin: Option<Json>,
    pub is_pep: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub pep_details: Option<Json>,
    pub is_sanctions_check_passed: Option<bool>,
    pub sanctions_check_date: Option<DateTimeWithTimeZone>,
    pub sanctions_provider: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub tags: Option<Vec<String>>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub verified_by: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub kyc_tier: Option<Json>,
    pub is_deleted: Option<bool>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
    #[sea_orm(has_many = "super::aml_alerts::Entity")]
    AmlAlerts,
    #[sea_orm(has_many = "super::card_disputes::Entity")]
    CardDisputes,
    #[sea_orm(has_many = "super::cards::Entity")]
    Cards,
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Countries,
    #[sea_orm(has_many = "super::credit_bureau_reports::Entity")]
    CreditBureauReports,
    #[sea_orm(has_many = "super::customer_address_verifications::Entity")]
    CustomerAddressVerifications,
    #[sea_orm(has_many = "super::customer_app_preferences::Entity")]
    CustomerAppPreferences,
    #[sea_orm(has_many = "super::customer_blacklist_records::Entity")]
    CustomerBlacklistRecords,
    #[sea_orm(has_many = "super::customer_identifications::Entity")]
    CustomerIdentifications,
    #[sea_orm(has_many = "super::customer_sessions::Entity")]
    CustomerSessions,
    #[sea_orm(has_many = "super::fee_applications::Entity")]
    FeeApplications,
    #[sea_orm(has_many = "super::field_officer_visits::Entity")]
    FieldOfficerVisits,
    #[sea_orm(has_many = "super::group_saving_members::Entity")]
    GroupSavingMembers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::kyc_provider_checks::Entity")]
    KycProviderChecks,
    #[sea_orm(has_many = "super::loan_applications::Entity")]
    LoanApplications,
    #[sea_orm(has_many = "super::loan_guarantors::Entity")]
    LoanGuarantors,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(has_many = "super::notification_preferences::Entity")]
    NotificationPreferences,
    #[sea_orm(has_many = "super::notification_queue::Entity")]
    NotificationQueue,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::VerifiedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(has_many = "super::staff_tasks::Entity")]
    StaffTasks,
    #[sea_orm(has_many = "super::support_tickets::Entity")]
    SupportTickets,
    #[sea_orm(has_many = "super::suspicious_transaction_reports::Entity")]
    SuspiciousTransactionReports,
    #[sea_orm(has_many = "super::tax_withholding::Entity")]
    TaxWithholding,
    #[sea_orm(has_many = "super::wallets::Entity")]
    Wallets,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::aml_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlAlerts.def()
    }
}

impl Related<super::card_disputes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardDisputes.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::credit_bureau_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBureauReports.def()
    }
}

impl Related<super::customer_address_verifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAddressVerifications.def()
    }
}

impl Related<super::customer_app_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAppPreferences.def()
    }
}

impl Related<super::customer_blacklist_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerBlacklistRecords.def()
    }
}

impl Related<super::customer_identifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerIdentifications.def()
    }
}

impl Related<super::customer_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerSessions.def()
    }
}

impl Related<super::fee_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeApplications.def()
    }
}

impl Related<super::field_officer_visits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FieldOfficerVisits.def()
    }
}

impl Related<super::group_saving_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupSavingMembers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::kyc_provider_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KycProviderChecks.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loan_guarantors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanGuarantors.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationPreferences.def()
    }
}

impl Related<super::notification_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationQueue.def()
    }
}

impl Related<super::staff_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTasks.def()
    }
}

impl Related<super::support_tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SupportTickets.def()
    }
}

impl Related<super::suspicious_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuspiciousTransactionReports.def()
    }
}

impl Related<super::tax_withholding::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxWithholding.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
