//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FeeWaiverWorkflowsApproval;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fee_waiver_workflows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub fee_application_id: Option<i64>,
    pub requested_by: i64,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub waiver_reason: String,
    pub approved_by: Option<i64>,
    pub approval_status: Option<FeeWaiverWorkflowsApproval>,
    pub approval_notes: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub requested_waiver_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub approved_waiver_amount: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fee_applications::Entity",
        from = "Column::FeeApplicationId",
        to = "super::fee_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    FeeApplications,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::RequestedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::fee_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeApplications.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
