//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FeeTypesCalcMethod;
use super::sea_orm_active_enums::FeeTypesCategory;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fee_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub fee_name: String,
    pub fee_code: String,
    pub fee_category: FeeTypesCategory,
    pub fee_calculation_method: FeeTypesCalcMethod,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub fee_value: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub minimum_fee: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub maximum_fee: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    pub is_vat_applicable: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub vat_rate: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_transaction_types: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_accounts: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_customers: Option<Json>,
    pub is_waiver_allowed: Option<bool>,
    pub is_waiver_approval_required: Option<bool>,
    pub is_active: Option<bool>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fee_applications::Entity")]
    FeeApplications,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::fee_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeApplications.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
