//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FeeApplicationRefType;
use super::sea_orm_active_enums::FeeApplicationStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fee_applications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub fee_type_id: i64,
    pub reference_id: Option<i64>,
    pub reference_type: Option<FeeApplicationRefType>,
    pub customer_id: Option<i64>,
    pub account_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub base_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub fee_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub vat_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub total_amount: Decimal,
    pub status: Option<FeeApplicationStatus>,
    pub waived_by: Option<i64>,
    pub waived_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub waiver_reason: Option<String>,
    pub waiver_approved_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::fee_types::Entity",
        from = "Column::FeeTypeId",
        to = "super::fee_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FeeTypes,
    #[sea_orm(has_many = "super::fee_waiver_workflows::Entity")]
    FeeWaiverWorkflows,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::WaivedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::WaiverApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::fee_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeTypes.def()
    }
}

impl Related<super::fee_waiver_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeWaiverWorkflows.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
