//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FieldOfficerVisitTypes;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "field_officer_visits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub route_id: i64,
    pub customer_id: i64,
    pub visit_order: i32,
    pub visit_type: Option<FieldOfficerVisitTypes>,
    pub scheduled_time: Option<DateTimeWithTimeZone>,
    pub arrival_time: Option<DateTimeWithTimeZone>,
    pub departure_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub customer_location: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub actual_visit_location: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub geo_accuracy_meters: Option<Decimal>,
    pub purpose: Option<String>,
    pub outcome: Option<String>,
    pub follow_up_required: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub expected_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub collected_amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub photos: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub signatures: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::field_officer_routes::Entity",
        from = "Column::RouteId",
        to = "super::field_officer_routes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FieldOfficerRoutes,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::field_officer_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FieldOfficerRoutes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
