//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccTypeStatus;
use super::sea_orm_active_enums::FdRolloverType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fixed_deposit_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub deposit_amount: Decimal,
    pub tenure_days: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub interest_rate: Decimal,
    pub maturity_date: Date,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub maturity_amount: Decimal,
    pub rollover_type: Option<FdRolloverType>,
    pub rollover_to_account_id: Option<i64>,
    pub is_early_withdrawal_allowed: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub early_withdrawal_penalty_rate: Option<Decimal>,
    pub status: Option<AccTypeStatus>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::RolloverToAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts1,
}

impl ActiveModelBehavior for ActiveModel {}
