//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::GenReportsDistStatus;
use super::sea_orm_active_enums::GenReportsFormat;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "generated_reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub schedule_id: Option<i64>,
    pub report_name: String,
    pub report_type: String,
    pub generated_at: Option<DateTimeWithTimeZone>,
    pub generated_by: Option<i64>,
    pub report_period_start: Date,
    pub report_period_end: Date,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub report_data: Option<Json>,
    pub report_data_size_bytes: Option<i32>,
    pub file_format: Option<GenReportsFormat>,
    pub file_path: Option<String>,
    pub file_url: Option<String>,
    pub file_checksum: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub distributed_to: Option<Json>,
    pub distribution_status: Option<GenReportsDistStatus>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::report_schedules::Entity",
        from = "Column::ScheduleId",
        to = "super::report_schedules::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ReportSchedules,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::GeneratedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::report_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportSchedules.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
