//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "gl_postings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_id: Option<i64>,
    pub reference_number: Option<String>,
    pub value_date: Date,
    pub posting_date: Option<DateTimeWithTimeZone>,
    pub debit_account_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub debit_amount: Decimal,
    pub credit_account_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub credit_amount: Decimal,
    #[sea_orm(column_type = "Text")]
    pub narration: String,
    pub is_reversed: Option<bool>,
    pub reversal_posting_id: Option<i64>,
    pub posted_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::CreditAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts2,
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::DebitAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts1,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ReversalPostingId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::PostedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Transactions,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
