//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::GlReversalsType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "gl_reversals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub original_posting_id: i64,
    pub reversal_posting_id: i64,
    #[sea_orm(column_type = "Text")]
    pub reversal_reason: String,
    pub reversal_type: GlReversalsType,
    pub approved_by: Option<i64>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub impact_assessment: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gl_postings::Entity",
        from = "Column::OriginalPostingId",
        to = "super::gl_postings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GlPostings2,
    #[sea_orm(
        belongs_to = "super::gl_postings::Entity",
        from = "Column::ReversalPostingId",
        to = "super::gl_postings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GlPostings1,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
