//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::GroupSavingMemberRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "group_saving_members")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub group_goal_id: i64,
    pub customer_id: i64,
    pub member_role: Option<GroupSavingMemberRole>,
    pub joined_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub committed_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub actual_contributed: Option<Decimal>,
    pub is_active: Option<bool>,
    pub exit_date: Option<Date>,
    pub exit_reason: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::saving_goals::Entity",
        from = "Column::GroupGoalId",
        to = "super::saving_goals::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SavingGoals,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::saving_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingGoals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
