//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IdemKeyStatus;
use super::sea_orm_active_enums::IdempotencyChannel;
use super::sea_orm_active_enums::IdempotencyOperation;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "idempotency_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub slug: String,
    pub institution_id: i64,
    pub customer_id: Option<i64>,
    pub account_id: Option<i64>,
    pub transaction_id: Option<i64>,
    pub transaction_group_id: Option<Uuid>,
    pub idempotency_key: String,
    pub operation: IdempotencyOperation,
    pub request_method: String,
    pub request_path: String,
    pub request_hash: String,
    pub channel: Option<IdempotencyChannel>,
    pub status: Option<IdemKeyStatus>,
    pub http_status: Option<i16>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response_body: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub locked_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
