//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "institutions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    pub code: Option<String>,
    pub country_id: i64,
    pub timezone: Option<String>,
    pub license_number: String,
    pub regulatory_number: String,
    pub logo_url: Option<String>,
    pub is_deleted: Option<bool>,
    pub is_active: Option<bool>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_categories::Entity")]
    AccountCategories,
    #[sea_orm(has_many = "super::account_links::Entity")]
    AccountLinks,
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
    #[sea_orm(has_many = "super::accruals_and_provisions::Entity")]
    AccrualsAndProvisions,
    #[sea_orm(has_many = "super::admin_audit_logs::Entity")]
    AdminAuditLogs,
    #[sea_orm(has_many = "super::agent_audits::Entity")]
    AgentAudits,
    #[sea_orm(has_many = "super::agent_commission_rules::Entity")]
    AgentCommissionRules,
    #[sea_orm(has_many = "super::agent_commissions::Entity")]
    AgentCommissions,
    #[sea_orm(has_many = "super::agent_performance::Entity")]
    AgentPerformance,
    #[sea_orm(has_many = "super::agent_settlements::Entity")]
    AgentSettlements,
    #[sea_orm(has_many = "super::agent_transactions::Entity")]
    AgentTransactions,
    #[sea_orm(has_many = "super::agent_wallets::Entity")]
    AgentWallets,
    #[sea_orm(has_many = "super::agents::Entity")]
    Agents,
    #[sea_orm(has_many = "super::aml_alerts::Entity")]
    AmlAlerts,
    #[sea_orm(has_many = "super::aml_rules::Entity")]
    AmlRules,
    #[sea_orm(has_many = "super::audit_trails::Entity")]
    AuditTrails,
    #[sea_orm(has_many = "super::branches::Entity")]
    Branches,
    #[sea_orm(has_many = "super::card_disputes::Entity")]
    CardDisputes,
    #[sea_orm(has_many = "super::card_transactions::Entity")]
    CardTransactions,
    #[sea_orm(has_many = "super::cards::Entity")]
    Cards,
    #[sea_orm(has_many = "super::cash_transfers::Entity")]
    CashTransfers,
    #[sea_orm(has_many = "super::chargebacks::Entity")]
    Chargebacks,
    #[sea_orm(has_many = "super::chart_of_accounts::Entity")]
    ChartOfAccounts,
    #[sea_orm(has_many = "super::commission_payouts::Entity")]
    CommissionPayouts,
    #[sea_orm(has_many = "super::contribution_cycles::Entity")]
    ContributionCycles,
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Countries,
    #[sea_orm(has_many = "super::credit_bureau_reports::Entity")]
    CreditBureauReports,
    #[sea_orm(has_many = "super::currency_transaction_reports::Entity")]
    CurrencyTransactionReports,
    #[sea_orm(has_many = "super::customer_app_preferences::Entity")]
    CustomerAppPreferences,
    #[sea_orm(has_many = "super::customer_blacklist_records::Entity")]
    CustomerBlacklistRecords,
    #[sea_orm(has_many = "super::customer_education_content::Entity")]
    CustomerEducationContent,
    #[sea_orm(has_many = "super::customer_sessions::Entity")]
    CustomerSessions,
    #[sea_orm(has_many = "super::customers::Entity")]
    Customers,
    #[sea_orm(has_many = "super::data_backups::Entity")]
    DataBackups,
    #[sea_orm(has_many = "super::data_retention_rules::Entity")]
    DataRetentionRules,
    #[sea_orm(has_many = "super::fee_applications::Entity")]
    FeeApplications,
    #[sea_orm(has_many = "super::fee_types::Entity")]
    FeeTypes,
    #[sea_orm(has_many = "super::fee_waiver_workflows::Entity")]
    FeeWaiverWorkflows,
    #[sea_orm(has_many = "super::field_officer_routes::Entity")]
    FieldOfficerRoutes,
    #[sea_orm(has_many = "super::financial_statements::Entity")]
    FinancialStatements,
    #[sea_orm(has_many = "super::generated_reports::Entity")]
    GeneratedReports,
    #[sea_orm(has_many = "super::gl_daily_balances::Entity")]
    GlDailyBalances,
    #[sea_orm(has_many = "super::gl_postings::Entity")]
    GlPostings,
    #[sea_orm(has_many = "super::gl_reversals::Entity")]
    GlReversals,
    #[sea_orm(has_many = "super::integration_api_keys::Entity")]
    IntegrationApiKeys,
    #[sea_orm(has_many = "super::integration_logs::Entity")]
    IntegrationLogs,
    #[sea_orm(has_many = "super::integration_providers::Entity")]
    IntegrationProviders,
    #[sea_orm(has_many = "super::integration_webhooks::Entity")]
    IntegrationWebhooks,
    #[sea_orm(has_many = "super::kyc_provider_checks::Entity")]
    KycProviderChecks,
    #[sea_orm(has_many = "super::ledger_lock_periods::Entity")]
    LedgerLockPeriods,
    #[sea_orm(has_many = "super::loan_applications::Entity")]
    LoanApplications,
    #[sea_orm(has_many = "super::loan_product_types::Entity")]
    LoanProductTypes,
    #[sea_orm(has_many = "super::loan_products::Entity")]
    LoanProducts,
    #[sea_orm(has_many = "super::loan_provisioning::Entity")]
    LoanProvisioning,
    #[sea_orm(has_many = "super::loan_repayments::Entity")]
    LoanRepayments,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(has_many = "super::maker_checker_workflows::Entity")]
    MakerCheckerWorkflows,
    #[sea_orm(has_many = "super::notification_preferences::Entity")]
    NotificationPreferences,
    #[sea_orm(has_many = "super::notification_queue::Entity")]
    NotificationQueue,
    #[sea_orm(has_many = "super::notification_templates::Entity")]
    NotificationTemplates,
    #[sea_orm(has_many = "super::product_change_workflows::Entity")]
    ProductChangeWorkflows,
    #[sea_orm(has_many = "super::product_visibility_rules::Entity")]
    ProductVisibilityRules,
    #[sea_orm(has_many = "super::refund_workflows::Entity")]
    RefundWorkflows,
    #[sea_orm(has_many = "super::regulatory_reporting_exports::Entity")]
    RegulatoryReportingExports,
    #[sea_orm(has_many = "super::regulatory_reports::Entity")]
    RegulatoryReports,
    #[sea_orm(has_many = "super::report_analytics_cache::Entity")]
    ReportAnalyticsCache,
    #[sea_orm(has_many = "super::report_schedules::Entity")]
    ReportSchedules,
    #[sea_orm(has_many = "super::saving_goals::Entity")]
    SavingGoals,
    #[sea_orm(has_many = "super::savings_products::Entity")]
    SavingsProducts,
    #[sea_orm(has_many = "super::sla_configurations::Entity")]
    SlaConfigurations,
    #[sea_orm(has_many = "super::staff::Entity")]
    Staff,
    #[sea_orm(has_many = "super::staff_commissions::Entity")]
    StaffCommissions,
    #[sea_orm(has_many = "super::staff_roles::Entity")]
    StaffRoles,
    #[sea_orm(has_many = "super::staff_tasks::Entity")]
    StaffTasks,
    #[sea_orm(has_many = "super::support_tickets::Entity")]
    SupportTickets,
    #[sea_orm(has_many = "super::suspicious_transaction_reports::Entity")]
    SuspiciousTransactionReports,
    #[sea_orm(has_many = "super::tax_withholding::Entity")]
    TaxWithholding,
    #[sea_orm(has_many = "super::tellers::Entity")]
    Tellers,
    #[sea_orm(has_many = "super::transaction_channels::Entity")]
    TransactionChannels,
    #[sea_orm(has_many = "super::transaction_limits::Entity")]
    TransactionLimits,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::vaults::Entity")]
    Vaults,
    #[sea_orm(has_many = "super::wallet_providers::Entity")]
    WalletProviders,
    #[sea_orm(has_many = "super::wallet_reconciliations::Entity")]
    WalletReconciliations,
    #[sea_orm(has_many = "super::wallet_transactions::Entity")]
    WalletTransactions,
    #[sea_orm(has_many = "super::wallets::Entity")]
    Wallets,
}

impl Related<super::account_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountCategories.def()
    }
}

impl Related<super::account_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountLinks.def()
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::accruals_and_provisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccrualsAndProvisions.def()
    }
}

impl Related<super::admin_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminAuditLogs.def()
    }
}

impl Related<super::agent_audits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentAudits.def()
    }
}

impl Related<super::agent_commission_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissionRules.def()
    }
}

impl Related<super::agent_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissions.def()
    }
}

impl Related<super::agent_performance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentPerformance.def()
    }
}

impl Related<super::agent_settlements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentSettlements.def()
    }
}

impl Related<super::agent_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentTransactions.def()
    }
}

impl Related<super::agent_wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentWallets.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::aml_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlAlerts.def()
    }
}

impl Related<super::aml_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlRules.def()
    }
}

impl Related<super::audit_trails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditTrails.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::card_disputes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardDisputes.def()
    }
}

impl Related<super::card_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardTransactions.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl Related<super::cash_transfers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashTransfers.def()
    }
}

impl Related<super::chargebacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chargebacks.def()
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::commission_payouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionPayouts.def()
    }
}

impl Related<super::contribution_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContributionCycles.def()
    }
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::credit_bureau_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBureauReports.def()
    }
}

impl Related<super::currency_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrencyTransactionReports.def()
    }
}

impl Related<super::customer_app_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAppPreferences.def()
    }
}

impl Related<super::customer_blacklist_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerBlacklistRecords.def()
    }
}

impl Related<super::customer_education_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerEducationContent.def()
    }
}

impl Related<super::customer_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerSessions.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::data_backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataBackups.def()
    }
}

impl Related<super::data_retention_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataRetentionRules.def()
    }
}

impl Related<super::fee_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeApplications.def()
    }
}

impl Related<super::fee_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeTypes.def()
    }
}

impl Related<super::fee_waiver_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeWaiverWorkflows.def()
    }
}

impl Related<super::field_officer_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FieldOfficerRoutes.def()
    }
}

impl Related<super::financial_statements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FinancialStatements.def()
    }
}

impl Related<super::generated_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedReports.def()
    }
}

impl Related<super::gl_daily_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlDailyBalances.def()
    }
}

impl Related<super::gl_postings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlPostings.def()
    }
}

impl Related<super::gl_reversals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlReversals.def()
    }
}

impl Related<super::integration_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationApiKeys.def()
    }
}

impl Related<super::integration_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationLogs.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl Related<super::integration_webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationWebhooks.def()
    }
}

impl Related<super::kyc_provider_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KycProviderChecks.def()
    }
}

impl Related<super::ledger_lock_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerLockPeriods.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loan_product_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProductTypes.def()
    }
}

impl Related<super::loan_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProducts.def()
    }
}

impl Related<super::loan_provisioning::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProvisioning.def()
    }
}

impl Related<super::loan_repayments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRepayments.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::maker_checker_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MakerCheckerWorkflows.def()
    }
}

impl Related<super::notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationPreferences.def()
    }
}

impl Related<super::notification_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationQueue.def()
    }
}

impl Related<super::notification_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTemplates.def()
    }
}

impl Related<super::product_change_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductChangeWorkflows.def()
    }
}

impl Related<super::product_visibility_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVisibilityRules.def()
    }
}

impl Related<super::refund_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundWorkflows.def()
    }
}

impl Related<super::regulatory_reporting_exports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegulatoryReportingExports.def()
    }
}

impl Related<super::regulatory_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegulatoryReports.def()
    }
}

impl Related<super::report_analytics_cache::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportAnalyticsCache.def()
    }
}

impl Related<super::report_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportSchedules.def()
    }
}

impl Related<super::saving_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingGoals.def()
    }
}

impl Related<super::savings_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsProducts.def()
    }
}

impl Related<super::sla_configurations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SlaConfigurations.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::staff_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffCommissions.def()
    }
}

impl Related<super::staff_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffRoles.def()
    }
}

impl Related<super::staff_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTasks.def()
    }
}

impl Related<super::support_tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SupportTickets.def()
    }
}

impl Related<super::suspicious_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuspiciousTransactionReports.def()
    }
}

impl Related<super::tax_withholding::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxWithholding.def()
    }
}

impl Related<super::tellers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tellers.def()
    }
}

impl Related<super::transaction_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionChannels.def()
    }
}

impl Related<super::transaction_limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionLimits.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::vaults::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vaults.def()
    }
}

impl Related<super::wallet_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletProviders.def()
    }
}

impl Related<super::wallet_reconciliations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletReconciliations.def()
    }
}

impl Related<super::wallet_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletTransactions.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
