//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "integration_api_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_id: Option<i64>,
    pub key_name: String,
    #[sea_orm(column_type = "Text")]
    pub api_key_encrypted: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_secret_encrypted: Option<String>,
    pub key_identifier: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub permissions: Option<Json>,
    pub allowed_ip_addresses: Option<Vec<String>>,
    pub key_status: Option<String>,
    pub issued_at: Option<DateTimeWithTimeZone>,
    pub valid_until: Option<DateTimeWithTimeZone>,
    pub usage_count: Option<i32>,
    pub last_used_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::integration_providers::Entity",
        from = "Column::ProviderId",
        to = "super::integration_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IntegrationProviders,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
