//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IntegrationProvidersProvStatus;
use super::sea_orm_active_enums::IntegrationProvidersServiceType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "integration_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_name: String,
    pub provider_code: String,
    pub service_type: IntegrationProvidersServiceType,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_base_url: Option<String>,
    pub api_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_key_encrypted: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_key_encrypted: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub webhook_secret: Option<String>,
    pub auth_method: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub oauth_config: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub jwt_config: Option<Json>,
    pub provider_status: Option<IntegrationProvidersProvStatus>,
    pub is_primary: Option<bool>,
    pub rate_limit_per_minute: Option<i32>,
    pub rate_limit_per_hour: Option<i32>,
    pub rate_limit_per_day: Option<i32>,
    pub retry_enabled: Option<bool>,
    pub max_retry_attempts: Option<i32>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credit_bureau_reports::Entity")]
    CreditBureauReports,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::integration_api_keys::Entity")]
    IntegrationApiKeys,
    #[sea_orm(has_many = "super::integration_logs::Entity")]
    IntegrationLogs,
    #[sea_orm(has_many = "super::integration_webhooks::Entity")]
    IntegrationWebhooks,
    #[sea_orm(has_many = "super::kyc_provider_checks::Entity")]
    KycProviderChecks,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::credit_bureau_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBureauReports.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationApiKeys.def()
    }
}

impl Related<super::integration_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationLogs.def()
    }
}

impl Related<super::integration_webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationWebhooks.def()
    }
}

impl Related<super::kyc_provider_checks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KycProviderChecks.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
