//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IntegrationWebhookStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "integration_webhooks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_id: Option<i64>,
    pub webhook_name: String,
    #[sea_orm(column_type = "Text")]
    pub endpoint_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_token_encrypted: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub subscribed_events: Json,
    pub auth_method: Option<String>,
    pub verify_ssl: Option<bool>,
    pub webhook_status: Option<IntegrationWebhookStatus>,
    pub last_delivery_at: Option<DateTimeWithTimeZone>,
    pub last_failure_at: Option<DateTimeWithTimeZone>,
    pub consecutive_failures: Option<i32>,
    pub max_retry_attempts: Option<i32>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::integration_providers::Entity",
        from = "Column::ProviderId",
        to = "super::integration_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IntegrationProviders,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
    #[sea_orm(has_many = "super::webhook_deliveries::Entity")]
    WebhookDeliveries,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::webhook_deliveries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookDeliveries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
