//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IntegrationLogStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "integration_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_id: i64,
    pub request_method: String,
    #[sea_orm(column_type = "Text")]
    pub request_url: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request_headers: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request_body: Option<Json>,
    pub response_status_code: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response_body: Option<Json>,
    pub response_time_ms: Option<i32>,
    pub status: Option<IntegrationLogStatus>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub error_code: Option<String>,
    pub reference_type: Option<String>,
    pub reference_id: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::integration_providers::Entity",
        from = "Column::ProviderId",
        to = "super::integration_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IntegrationProviders,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
