//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "kyc_provider_checks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub provider_id: i64,
    pub customer_id: i64,
    pub check_type: String,
    pub identification_id: Option<i64>,
    pub check_status: String,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub verification_score: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub verification_data: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub submitted_image_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verified_image_url: Option<String>,
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customer_identifications::Entity",
        from = "Column::IdentificationId",
        to = "super::customer_identifications::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CustomerIdentifications,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::integration_providers::Entity",
        from = "Column::ProviderId",
        to = "super::integration_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IntegrationProviders,
}

impl Related<super::customer_identifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerIdentifications.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
