//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanProductCalcMethod;
use super::sea_orm_active_enums::LoanProductFreq;
use super::sea_orm_active_enums::LoanProductInterestType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub loan_product_type_id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub minimum_principal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub maximum_principal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub default_principal: Option<Decimal>,
    pub minimum_tenure_days: i32,
    pub maximum_tenure_days: i32,
    pub default_tenure_days: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub interest_rate: Decimal,
    pub interest_rate_type: Option<LoanProductInterestType>,
    pub interest_calc_method: Option<LoanProductCalcMethod>,
    pub interest_accural_freq: Option<LoanProductFreq>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub processing_fee_rate: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub processing_fee_flat: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub insurance_fee_rate: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub insurance_fee_flat: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub late_payment_penalty_rate: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub late_payment_penalty_flat: Option<Decimal>,
    pub penalty_grace_period_days: Option<i32>,
    pub repayment_freq: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub allowed_repayment_methods: Option<Json>,
    pub minimum_credit_score: Option<i32>,
    pub max_age: Option<i32>,
    pub min_age: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub allowed_customer_types: Option<Json>,
    pub is_collateral_required: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub minimum_collateral_ratio: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub allowed_collateral_types: Option<Json>,
    pub is_guarantor_required: Option<bool>,
    pub minimum_guarantors: Option<i32>,
    pub is_active: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub visibility: Option<Json>,
    pub loan_gl_account_id: Option<i64>,
    pub interest_gl_account_id: Option<i64>,
    pub penalty_gl_account_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub required_kyc: Option<Json>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::InterestGlAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts3,
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::LoanGlAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts2,
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::PenaltyGlAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts1,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::loan_applications::Entity")]
    LoanApplications,
    #[sea_orm(
        belongs_to = "super::loan_product_types::Entity",
        from = "Column::LoanProductTypeId",
        to = "super::loan_product_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanProductTypes,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loan_product_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProductTypes.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
