//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_application_status_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_application_id: i64,
    pub from_status: Option<String>,
    pub to_status: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub transition_reason: Option<Json>,
    pub changed_at: Option<DateTimeWithTimeZone>,
    pub changed_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanApplications,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ChangedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
