//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanApplicationStatus;
use super::sea_orm_active_enums::LoanRiskRating;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_applications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub loan_product_id: i64,
    pub customer_id: i64,
    #[sea_orm(unique)]
    pub application_number: Option<String>,
    pub status: Option<LoanApplicationStatus>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub requested_principal: Decimal,
    pub requested_tenure_days: i32,
    pub purpose: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub approved_principal: Option<Decimal>,
    pub approved_tenure_days: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub approved_interest_rate: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub installment_amount: Option<Decimal>,
    pub credit_score: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub credit_bureau_response: Option<Json>,
    pub risk_rating: Option<LoanRiskRating>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub documents_provided: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub documents_missing: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub application_data: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub employment_details: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub financial_details: Option<Json>,
    pub submitted_at: Option<DateTimeWithTimeZone>,
    pub current_stage: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub approval_conditions: Option<Json>,
    pub rejected_reason: Option<String>,
    pub rejected_at: Option<DateTimeWithTimeZone>,
    pub submitted_by: Option<i64>,
    pub assigned_officer: Option<i64>,
    pub approved_by: Option<i64>,
    pub rejected_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credit_bureau_reports::Entity")]
    CreditBureauReports,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::loan_application_status_history::Entity")]
    LoanApplicationStatusHistory,
    #[sea_orm(has_many = "super::loan_collaterals::Entity")]
    LoanCollaterals,
    #[sea_orm(has_many = "super::loan_guarantors::Entity")]
    LoanGuarantors,
    #[sea_orm(
        belongs_to = "super::loan_products::Entity",
        from = "Column::LoanProductId",
        to = "super::loan_products::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanProducts,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff4,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedOfficer",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff3,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::RejectedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::SubmittedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(has_many = "super::staff_tasks::Entity")]
    StaffTasks,
}

impl Related<super::credit_bureau_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBureauReports.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_application_status_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplicationStatusHistory.def()
    }
}

impl Related<super::loan_collaterals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanCollaterals.def()
    }
}

impl Related<super::loan_guarantors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanGuarantors.def()
    }
}

impl Related<super::loan_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProducts.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::staff_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
