//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanCollateralTypes;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_collaterals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_application_id: i64,
    pub loan_id: Option<i64>,
    pub collateral_type: Option<LoanCollateralTypes>,
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub estimated_value: Decimal,
    pub valuation_date: Date,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub document_urls: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub ownership_documents: Option<Json>,
    pub is_verified: Option<bool>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub is_released: Option<bool>,
    pub released_at: Option<DateTimeWithTimeZone>,
    pub release_reason: Option<String>,
    pub verified_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanApplications,
    #[sea_orm(has_many = "super::loan_collateral_valuations::Entity")]
    LoanCollateralValuations,
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loans,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::VerifiedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loan_collateral_valuations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanCollateralValuations.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
