//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanRepaymentScheduleStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_repayment_schedules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_id: i64,
    pub installment_number: i32,
    pub due_date: Date,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub principal_due: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub interest_due: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub total_due: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub principal_paid: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub interest_paid: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub penalty_paid: Option<Decimal>,
    pub status: Option<LoanRepaymentScheduleStatus>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loans,
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
