//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_write_offs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub write_off_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub outstanding_principal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub outstanding_interest: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub outstanding_penalty: Decimal,
    pub write_off_reason: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub provision_amount: Option<Decimal>,
    pub written_off_at: Option<DateTimeWithTimeZone>,
    pub written_off_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loans,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::WrittenOffBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
