//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_collateral_valuations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub collateral_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub valuation_amount: Decimal,
    pub valuation_date: Date,
    pub valuator_name: Option<String>,
    pub valuation_report_url: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loan_collaterals::Entity",
        from = "Column::CollateralId",
        to = "super::loan_collaterals::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanCollaterals,
}

impl Related<super::loan_collaterals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanCollaterals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
