//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanApplicationStatus;
use super::sea_orm_active_enums::LoanRepaymentFreq;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub loan_application_id: i64,
    pub loan_product_id: i64,
    pub customer_id: i64,
    pub account_id: i64,
    #[sea_orm(unique)]
    pub loan_account_number: String,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub principal_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub disbursed_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub outstanding_principal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub outstanding_interest: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub outstanding_penalty: Option<Decimal>,
    pub tenure_days: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub interest_rate: Decimal,
    pub repayment_freq: Option<LoanRepaymentFreq>,
    pub application_date: Date,
    pub approval_date: Option<Date>,
    pub disbursement_date: Option<Date>,
    pub first_repayment_date: Option<Date>,
    pub last_repayment_date: Option<Date>,
    pub maturity_date: Date,
    pub status: Option<LoanApplicationStatus>,
    pub is_npa: Option<bool>,
    pub npa_classification_date: Option<Date>,
    pub days_in_arrears: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub arrears_amount: Option<Decimal>,
    pub days_to_write_off: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub provision_rate: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub provision_amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanApplications,
    #[sea_orm(has_many = "super::loan_collaterals::Entity")]
    LoanCollaterals,
    #[sea_orm(has_many = "super::loan_guarantors::Entity")]
    LoanGuarantors,
    #[sea_orm(has_many = "super::loan_penalties::Entity")]
    LoanPenalties,
    #[sea_orm(
        belongs_to = "super::loan_products::Entity",
        from = "Column::LoanProductId",
        to = "super::loan_products::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanProducts,
    #[sea_orm(has_many = "super::loan_provisioning::Entity")]
    LoanProvisioning,
    #[sea_orm(has_many = "super::loan_repayment_schedules::Entity")]
    LoanRepaymentSchedules,
    #[sea_orm(has_many = "super::loan_repayments::Entity")]
    LoanRepayments,
    #[sea_orm(has_one = "super::loan_rescheduling::Entity")]
    LoanRescheduling,
    #[sea_orm(has_many = "super::loan_write_offs::Entity")]
    LoanWriteOffs,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loan_collaterals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanCollaterals.def()
    }
}

impl Related<super::loan_guarantors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanGuarantors.def()
    }
}

impl Related<super::loan_penalties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanPenalties.def()
    }
}

impl Related<super::loan_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProducts.def()
    }
}

impl Related<super::loan_provisioning::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProvisioning.def()
    }
}

impl Related<super::loan_repayment_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRepaymentSchedules.def()
    }
}

impl Related<super::loan_repayments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRepayments.def()
    }
}

impl Related<super::loan_rescheduling::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRescheduling.def()
    }
}

impl Related<super::loan_write_offs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanWriteOffs.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
