//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::LoanPenaltyStatus;
use super::sea_orm_active_enums::LoanPenaltyType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_penalties")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_id: i64,
    pub installment_number: i32,
    pub penalty_type: Option<LoanPenaltyType>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub penalty_amount: Option<Decimal>,
    pub calculated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub waived_amount: Option<Decimal>,
    pub waived_at: Option<DateTimeWithTimeZone>,
    pub waive_reason: Option<String>,
    pub status: Option<LoanPenaltyStatus>,
    pub waived_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loans,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::WaivedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
