//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "loan_guarantors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub loan_application_id: i64,
    pub loan_id: Option<i64>,
    pub customer_id: Option<i64>,
    pub guarantor_name: Option<String>,
    pub guarantor_id_number: Option<String>,
    pub guarantor_phone: Option<String>,
    pub guarantor_email: Option<String>,
    pub guarantor_address: Option<String>,
    pub guarantor_relationship: Option<String>,
    pub guarantor_occupation: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub guarantor_income: Option<Decimal>,
    pub agreement_document_url: Option<String>,
    pub is_consent_provided: Option<bool>,
    pub consent_date: Option<DateTimeWithTimeZone>,
    pub is_active: Option<bool>,
    pub accepted_at: Option<DateTimeWithTimeZone>,
    pub released_at: Option<DateTimeWithTimeZone>,
    pub release_reason: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanApplications,
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loans,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
