//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::MakerCheckerCheckerAction;
use super::sea_orm_active_enums::MakerCheckerReferenceType;
use super::sea_orm_active_enums::MakerCheckerStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "maker_checker_workflows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub reference_type: MakerCheckerReferenceType,
    pub reference_id: i64,
    pub maker_id: i64,
    pub maker_action: String,
    pub maker_notes: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub request_data: Json,
    pub checker_id: Option<i64>,
    pub checker_action: Option<MakerCheckerCheckerAction>,
    pub checker_notes: Option<String>,
    pub checked_at: Option<DateTimeWithTimeZone>,
    pub status: Option<MakerCheckerStatus>,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub implemented_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub implementation_result: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CheckerId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::MakerId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
