//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::NotificationQueueStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_queue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: Option<i64>,
    pub staff_id: Option<i64>,
    pub agent_id: Option<i64>,
    pub recipient_contact: Option<String>,
    pub recipient_device_id: Option<String>,
    pub template_id: Option<i64>,
    pub notification_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub subject: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub variables: Option<Json>,
    pub status: Option<NotificationQueueStatus>,
    pub priority: Option<i32>,
    pub scheduled_at: Option<DateTimeWithTimeZone>,
    pub sent_at: Option<DateTimeWithTimeZone>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub failed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_reason: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub provider_response: Option<Json>,
    pub provider_message_id: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::notification_templates::Entity",
        from = "Column::TemplateId",
        to = "super::notification_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NotificationTemplates,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::notification_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTemplates.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
