//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::NotificationType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub template_name: String,
    pub template_code: String,
    pub notification_type: NotificationType,
    pub subject_template: Option<String>,
    pub body_template: String,
    pub language_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub required_variables: Option<Json>,
    pub sms_sender: Option<String>,
    pub email_template_html: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub push_notification_data: Option<Json>,
    pub is_active: Option<bool>,
    pub is_default: Option<bool>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::notification_queue::Entity")]
    NotificationQueue,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::notification_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationQueue.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
