//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "product_visibility_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub product_type: String,
    pub product_id: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub visible_to_branches: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub visible_to_customers: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub visible_to_kyc_tiers: Option<Json>,
    pub min_customer_age: Option<i32>,
    pub max_customer_age: Option<i32>,
    pub min_credit_score: Option<i32>,
    pub is_active: Option<bool>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
