//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ProductWorkflowsProductType;
use super::sea_orm_active_enums::ProductWorkflowsStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "product_change_workflows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub product_type: ProductWorkflowsProductType,
    pub product_id: i64,
    #[sea_orm(column_type = "Text")]
    pub change_description: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub old_config: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub new_config: Option<Json>,
    pub requester_id: i64,
    pub approver_id: Option<i64>,
    pub status: Option<ProductWorkflowsStatus>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rejection_reason: Option<String>,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub implemented_at: Option<DateTimeWithTimeZone>,
    pub implemented_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApproverId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff3,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ImplementedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::RequesterId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
