//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::RefundWorkflowApprovalStatus;
use super::sea_orm_active_enums::RefundWorkflowRefundType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "refund_workflows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_id: i64,
    pub dispute_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub refund_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub fee_refund_amount: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub refund_reason: String,
    pub refund_type: RefundWorkflowRefundType,
    pub requester_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub requester_notes: Option<String>,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub approver_id: Option<i64>,
    pub approval_status: Option<RefundWorkflowApprovalStatus>,
    #[sea_orm(column_type = "Text", nullable)]
    pub approval_notes: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub processed_by: Option<i64>,
    pub processed_at: Option<DateTimeWithTimeZone>,
    pub refund_reference: Option<String>,
    pub refund_to_account_id: Option<i64>,
    pub refund_to_wallet_id: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::RefundToAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApproverId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff3,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ProcessedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::RequesterId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::RefundToWalletId",
        to = "super::wallets::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Wallets,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
