//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ReportCategory;
use super::sea_orm_active_enums::ReportFrequency;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_schedules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub institution_id: i64,
    pub report_name: String,
    pub report_type: String,
    pub report_category: Option<ReportCategory>,
    pub frequency: ReportFrequency,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub schedule_config: Option<Json>,
    pub next_run_at: Option<DateTimeWithTimeZone>,
    pub last_run_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub recipients: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub report_parameters: Option<Json>,
    pub is_active: Option<bool>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::generated_reports::Entity")]
    GeneratedReports,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::generated_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedReports.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
