//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_analytics_cache")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub report_type: String,
    pub cache_key: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub cached_data: Json,
    pub data_hash: Option<String>,
    pub generated_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub generation_time_ms: Option<i32>,
    pub data_size_bytes: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
