//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SavingsProductFreq;
use super::sea_orm_active_enums::SavingsProductInterestCalc;
use super::sea_orm_active_enums::SavingsProductPayoutFreq;
use super::sea_orm_active_enums::SavingsProductType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "savings_products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub description: Option<String>,
    pub savings_type: Option<SavingsProductType>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub min_contribution: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub max_contribution: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub default_contribution: Option<Decimal>,
    pub contribution_freq: Option<SavingsProductFreq>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub interest_rate: Option<Decimal>,
    pub interest_calc_method: Option<SavingsProductInterestCalc>,
    pub interest_payout_freq: Option<SavingsProductPayoutFreq>,
    pub lock_period_days: Option<i32>,
    pub withdrawal_restriction_days: Option<i32>,
    pub is_early_withdrawal_allowed: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))", nullable)]
    pub early_withdrawal_penalty_rate: Option<Decimal>,
    pub is_target_amount_enabled: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub min_target_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub max_target_amount: Option<Decimal>,
    pub is_group_savings_allowed: Option<bool>,
    pub min_group_members: Option<i32>,
    pub max_group_members: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub missed_contribution_penalty: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub maintenance_fee: Option<Decimal>,
    pub is_active: Option<bool>,
    pub created_by: Option<i64>,
    pub requires_approval: Option<bool>,
    pub gl_account_id: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::GlAccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChartOfAccounts,
    #[sea_orm(has_many = "super::contribution_cycles::Entity")]
    ContributionCycles,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::saving_goals::Entity")]
    SavingGoals,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::contribution_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContributionCycles.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::saving_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingGoals.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
