//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SavingGoalsStatus;
use super::sea_orm_active_enums::SavingsProductFreq;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "saving_goals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub savings_product_id: i64,
    pub account_id: i64,
    pub goal_name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub target_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub current_amount: Option<Decimal>,
    pub start_date: Date,
    pub target_completion_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub contribution_amount: Option<Decimal>,
    pub contribution_freq: Option<SavingsProductFreq>,
    pub status: Option<SavingGoalsStatus>,
    pub completion_date: Option<Date>,
    pub progress_percentage: Option<i32>,
    pub is_group_savings: Option<bool>,
    pub group_owner_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers2,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::GroupOwnerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers1,
    #[sea_orm(has_many = "super::group_saving_members::Entity")]
    GroupSavingMembers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::savings_products::Entity",
        from = "Column::SavingsProductId",
        to = "super::savings_products::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SavingsProducts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::group_saving_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupSavingMembers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::savings_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsProducts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
