//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "acc_limit_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccLimitType {
    #[sea_orm(string_value = "DAILY_DEBIT")]
    DailyDebit,
    #[sea_orm(string_value = "DAILY_CREDIT")]
    DailyCredit,
    #[sea_orm(string_value = "DAILY_TRANSACTION_COUNT")]
    DailyTransactionCount,
    #[sea_orm(string_value = "WEEKLY_DEBIT")]
    WeeklyDebit,
    #[sea_orm(string_value = "MONTHLY_DEBIT")]
    MonthlyDebit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "acc_link_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccLinkType {
    #[sea_orm(string_value = "JOINT")]
    Joint,
    #[sea_orm(string_value = "TRUST")]
    Trust,
    #[sea_orm(string_value = "CORPORATE")]
    Corporate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "acc_reset_freq_type"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AccResetFreqType {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "acc_type_int_calc")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccTypeIntCalc {
    #[sea_orm(string_value = "SIMPLE")]
    Simple,
    #[sea_orm(string_value = "COMPOUND")]
    Compound,
    #[sea_orm(string_value = "DAILY")]
    Daily,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "acc_type_int_payout_freq"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AccTypeIntPayoutFreq {
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "QUATERLY")]
    Quaterly,
    #[sea_orm(string_value = "YEARLY")]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "acc_type_status")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccTypeStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "DORMANT")]
    Dormant,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
    #[sea_orm(string_value = "FROZEN")]
    Frozen,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
    #[sea_orm(string_value = "SUSPENDED")]
    Suspended,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "accrual_reference_type"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AccrualReferenceType {
    #[sea_orm(string_value = "LOAN")]
    Loan,
    #[sea_orm(string_value = "SAVINGS")]
    Savings,
    #[sea_orm(string_value = "INVESTMENT")]
    Investment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "accrual_status")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccrualStatus {
    #[sea_orm(string_value = "ACCRUED")]
    Accrued,
    #[sea_orm(string_value = "POSTED")]
    Posted,
    #[sea_orm(string_value = "REVERSED")]
    Reversed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "accrual_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AccrualType {
    #[sea_orm(string_value = "INTEREST_ACCRUAL")]
    InterestAccrual,
    #[sea_orm(string_value = "FEE_ACCRUAL")]
    FeeAccrual,
    #[sea_orm(string_value = "PROVISION")]
    Provision,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_commission_rule_comm_type"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentCommissionRuleCommType {
    #[sea_orm(string_value = "PERCENTAGE")]
    Percentage,
    #[sea_orm(string_value = "FLAT")]
    Flat,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_commissions_status"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentCommissionsStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_commissions_trans_type"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentCommissionsTransType {
    #[sea_orm(string_value = "DEPOSIT")]
    Deposit,
    #[sea_orm(string_value = "WITHDRAWAL")]
    Withdrawal,
    #[sea_orm(string_value = "LOAN_REPAYMENT")]
    LoanRepayment,
    #[sea_orm(string_value = "BILL_PAYMENT")]
    BillPayment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "agent_entity_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentEntityType {
    #[sea_orm(string_value = "INDIVIDUAL")]
    Individual,
    #[sea_orm(string_value = "BUSINESS")]
    Business,
    #[sea_orm(string_value = "SACCO")]
    Sacco,
    #[sea_orm(string_value = "GROUP")]
    Group,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_kyc_docs_doctype"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentKycDocsDoctype {
    #[sea_orm(string_value = "ID")]
    Id,
    #[sea_orm(string_value = "BUSINESS_CERT")]
    BusinessCert,
    #[sea_orm(string_value = "UTILITY_BILL")]
    UtilityBill,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_settlement_channels"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentSettlementChannels {
    #[sea_orm(string_value = "BANK_TRANSFER")]
    BankTransfer,
    #[sea_orm(string_value = "MOBILE_MONEY")]
    MobileMoney,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_settlement_status"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentSettlementStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "agent_status")]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "SUSPENDED")]
    Suspended,
    #[sea_orm(string_value = "TERMINATED")]
    Terminated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "agent_trans_status")]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentTransStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "agent_trans_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentTransType {
    #[sea_orm(string_value = "CASH_DEPOSIT")]
    CashDeposit,
    #[sea_orm(string_value = "CASH_WITHDRAWAL")]
    CashWithdrawal,
    #[sea_orm(string_value = "WALLET_TOPUP")]
    WalletTopup,
    #[sea_orm(string_value = "WALLET_WITHDRAWAL")]
    WalletWithdrawal,
    #[sea_orm(string_value = "LOAN_REPAYMENT")]
    LoanRepayment,
    #[sea_orm(string_value = "BILL_PAYMENT")]
    BillPayment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "agent_wallet_status"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentWalletStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "agent_wallet_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum AgentWalletType {
    #[sea_orm(string_value = "FLOAT")]
    Float,
    #[sea_orm(string_value = "COMMISSION")]
    Commission,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "aml_alerts_status")]
#[serde(rename_all = "UPPERCASE")]
pub enum AmlAlertsStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "INVESTIGATING")]
    Investigating,
    #[sea_orm(string_value = "RESOLVED")]
    Resolved,
    #[sea_orm(string_value = "FALSE_POSITIVE")]
    FalsePositive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "aml_risk_level_enum"
)]
#[serde(rename_all = "UPPERCASE")]
pub enum AmlRiskLevelEnum {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "aml_rules_action_on_trigger"
)]
pub enum AmlRulesActionOnTrigger {
    #[sea_orm(string_value = "FLAG")]
    Flag,
    #[sea_orm(string_value = "FREEZE_ACCOUNT")]
    FreezeAccount,
    #[sea_orm(string_value = "ALERT")]
    Alert,
    #[sea_orm(string_value = "BLOCK_TRANSACTION")]
    BlockTransaction,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "aml_rules_rule_type"
)]
pub enum AmlRulesRuleType {
    #[sea_orm(string_value = "VELOCITY")]
    Velocity,
    #[sea_orm(string_value = "STRUCTURING")]
    Structuring,
    #[sea_orm(string_value = "SANCTIONS")]
    Sanctions,
    #[sea_orm(string_value = "PEP")]
    Pep,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "audit_trails_action"
)]
pub enum AuditTrailsAction {
    #[sea_orm(string_value = "CREATE")]
    Create,
    #[sea_orm(string_value = "UPDATE")]
    Update,
    #[sea_orm(string_value = "DELETE")]
    Delete,
    #[sea_orm(string_value = "VIEW")]
    View,
    #[sea_orm(string_value = "APPROVE")]
    Approve,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "audit_trails_resource_type"
)]
pub enum AuditTrailsResourceType {
    #[sea_orm(string_value = "ACCOUNT")]
    Account,
    #[sea_orm(string_value = "TRANSACTION")]
    Transaction,
    #[sea_orm(string_value = "CUSTOMER")]
    Customer,
    #[sea_orm(string_value = "LOAN")]
    Loan,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "audit_trails_user_type"
)]
pub enum AuditTrailsUserType {
    #[sea_orm(string_value = "STAFF")]
    Staff,
    #[sea_orm(string_value = "CUSTOMER")]
    Customer,
    #[sea_orm(string_value = "SYSTEM")]
    System,
    #[sea_orm(string_value = "API")]
    Api,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_brand")]
pub enum CardBrand {
    #[sea_orm(string_value = "VISA")]
    Visa,
    #[sea_orm(string_value = "MASTERCARD")]
    Mastercard,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "card_dispute_status"
)]
pub enum CardDisputeStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "INVESTIGATION")]
    Investigation,
    #[sea_orm(string_value = "WON")]
    Won,
    #[sea_orm(string_value = "LOST")]
    Lost,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_dispute_type")]
pub enum CardDisputeType {
    #[sea_orm(string_value = "FRAUD")]
    Fraud,
    #[sea_orm(string_value = "DUPLICATE")]
    Duplicate,
    #[sea_orm(string_value = "NOT_RECEIVED")]
    NotReceived,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_form")]
pub enum CardForm {
    #[sea_orm(string_value = "PHYSICAL")]
    Physical,
    #[sea_orm(string_value = "VIRTUAL")]
    Virtual,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_limit_reset")]
pub enum CardLimitReset {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "QUARTERLY")]
    Quarterly,
    #[sea_orm(string_value = "YEARLY")]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_limit_type")]
pub enum CardLimitType {
    #[sea_orm(string_value = "ATM_WITHDRAWAL")]
    AtmWithdrawal,
    #[sea_orm(string_value = "POS_PURCHASE")]
    PosPurchase,
    #[sea_orm(string_value = "ONLINE_PURCHASE")]
    OnlinePurchase,
    #[sea_orm(string_value = "DAILY_TOTAL")]
    DailyTotal,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_status")]
pub enum CardStatus {
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "BLOCKED")]
    Blocked,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "FROZEN")]
    Frozen,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "card_transactions_status"
)]
pub enum CardTransactionsStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "DECLINED")]
    Declined,
    #[sea_orm(string_value = "REVERSED")]
    Reversed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "card_transactions_trans_channel"
)]
pub enum CardTransactionsTransChannel {
    #[sea_orm(string_value = "DOMESTIC")]
    Domestic,
    #[sea_orm(string_value = "INTERNATIONAL")]
    International,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "card_transactions_trans_type"
)]
pub enum CardTransactionsTransType {
    #[sea_orm(string_value = "ATM")]
    Atm,
    #[sea_orm(string_value = "POS")]
    Pos,
    #[sea_orm(string_value = "ONLINE")]
    Online,
    #[sea_orm(string_value = "CONTACTLESS")]
    Contactless,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "card_type")]
pub enum CardType {
    #[sea_orm(string_value = "DEBIT")]
    Debit,
    #[sea_orm(string_value = "CREDIT")]
    Credit,
    #[sea_orm(string_value = "PREPAID")]
    Prepaid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "cash_transfers_status"
)]
pub enum CashTransfersStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "cash_transfers_type"
)]
pub enum CashTransfersType {
    #[sea_orm(string_value = "VAULT")]
    Vault,
    #[sea_orm(string_value = "TELLER_DRAWER")]
    TellerDrawer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "chargeback_status")]
pub enum ChargebackStatus {
    #[sea_orm(string_value = "INITIATED")]
    Initiated,
    #[sea_orm(string_value = "INVESTIGATION")]
    Investigation,
    #[sea_orm(string_value = "WON")]
    Won,
    #[sea_orm(string_value = "LOST")]
    Lost,
    #[sea_orm(string_value = "ARBITRATION")]
    Arbitration,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "comm_payout_status")]
pub enum CommPayoutStatus {
    #[sea_orm(string_value = "PROCESSING")]
    Processing,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "contribution_cycles_status"
)]
pub enum ContributionCyclesStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "contribution_status"
)]
pub enum ContributionStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "contribution_type")]
pub enum ContributionType {
    #[sea_orm(string_value = "REGULAR")]
    Regular,
    #[sea_orm(string_value = "PENALTY")]
    Penalty,
    #[sea_orm(string_value = "BONUS")]
    Bonus,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "currency_report_type"
)]
pub enum CurrencyReportType {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "customer_sessions_status"
)]
pub enum CustomerSessionsStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "customer_type")]
#[serde(rename_all = "UPPERCASE")]
pub enum CustomerType {
    #[sea_orm(string_value = "INDIVIDUAL")]
    Individual,
    #[sea_orm(string_value = "SME")]
    Sme,
    #[sea_orm(string_value = "GROUP")]
    Group,
    #[sea_orm(string_value = "COOPERATIVE")]
    Cooperative,
    #[sea_orm(string_value = "CORPORATE")]
    Corporate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "data_backup_status")]
pub enum DataBackupStatus {
    #[sea_orm(string_value = "RUNNING")]
    Running,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "SCHEDULED")]
    Scheduled,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "data_retention_action_after_retention"
)]
pub enum DataRetentionActionAfterRetention {
    #[sea_orm(string_value = "ARCHIVE")]
    Archive,
    #[sea_orm(string_value = "DELETE")]
    Delete,
    #[sea_orm(string_value = "ANONYMIZE")]
    Anonymize,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "data_retention_category"
)]
pub enum DataRetentionCategory {
    #[sea_orm(string_value = "TRANSACTIONS")]
    Transactions,
    #[sea_orm(string_value = "AUDIT_LOGS")]
    AuditLogs,
    #[sea_orm(string_value = "CUSTOMER_DATA")]
    CustomerData,
    #[sea_orm(string_value = "DOCUMENTS")]
    Documents,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "fd_rollover_type")]
pub enum FdRolloverType {
    #[sea_orm(string_value = "NONE")]
    None,
    #[sea_orm(string_value = "PRINCIPAL")]
    Principal,
    #[sea_orm(string_value = "PRINCIPAL_AND_INTEREST")]
    PrincipalAndInterest,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "fee_application_ref_type"
)]
pub enum FeeApplicationRefType {
    #[sea_orm(string_value = "TRANSACTION")]
    Transaction,
    #[sea_orm(string_value = "ACCOUNT")]
    Account,
    #[sea_orm(string_value = "LOAN")]
    Loan,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "fee_application_status"
)]
pub enum FeeApplicationStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "CHARGED")]
    Charged,
    #[sea_orm(string_value = "WAIVED")]
    Waived,
    #[sea_orm(string_value = "REVERSED")]
    Reversed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "fee_types_calc_method"
)]
pub enum FeeTypesCalcMethod {
    #[sea_orm(string_value = "PERCENTAGE")]
    Percentage,
    #[sea_orm(string_value = "FLAT")]
    Flat,
    #[sea_orm(string_value = "TIERED")]
    Tiered,
    #[sea_orm(string_value = "SLAB")]
    Slab,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "fee_types_category")]
pub enum FeeTypesCategory {
    #[sea_orm(string_value = "TRANSACTION")]
    Transaction,
    #[sea_orm(string_value = "MAINTENANCE")]
    Maintenance,
    #[sea_orm(string_value = "LOAN_PROCESSING")]
    LoanProcessing,
    #[sea_orm(string_value = "CARD")]
    Card,
    #[sea_orm(string_value = "PENALTY")]
    Penalty,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "fee_waiver_workflows_approval"
)]
pub enum FeeWaiverWorkflowsApproval {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "field_officer_routes_status"
)]
pub enum FieldOfficerRoutesStatus {
    #[sea_orm(string_value = "PLANNED")]
    Planned,
    #[sea_orm(string_value = "IN_PROGRESS")]
    InProgress,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "field_officer_visit_types"
)]
pub enum FieldOfficerVisitTypes {
    #[sea_orm(string_value = "COLLECTION")]
    Collection,
    #[sea_orm(string_value = "VERIFICATION")]
    Verification,
    #[sea_orm(string_value = "DISBURSEMENT")]
    Disbursement,
    #[sea_orm(string_value = "RECOVERY")]
    Recovery,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gen_report_status")]
pub enum GenReportStatus {
    #[sea_orm(string_value = "GENERATING")]
    Generating,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "gen_reports_dist_status"
)]
pub enum GenReportsDistStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gen_reports_format")]
pub enum GenReportsFormat {
    #[sea_orm(string_value = "PDF")]
    Pdf,
    #[sea_orm(string_value = "EXCEL")]
    Excel,
    #[sea_orm(string_value = "CSV")]
    Csv,
    #[sea_orm(string_value = "JSON")]
    Json,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gl_reversals_type")]
pub enum GlReversalsType {
    #[sea_orm(string_value = "ERROR")]
    Error,
    #[sea_orm(string_value = "FRAUD")]
    Fraud,
    #[sea_orm(string_value = "CUSTOMER_REQUEST")]
    CustomerRequest,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "group_saving_member_role"
)]
pub enum GroupSavingMemberRole {
    #[sea_orm(string_value = "MEMBER")]
    Member,
    #[sea_orm(string_value = "LEADER")]
    Leader,
    #[sea_orm(string_value = "ADMIN")]
    Admin,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "health_status")]
pub enum HealthStatus {
    #[sea_orm(string_value = "HEALTHY")]
    Healthy,
    #[sea_orm(string_value = "UNHEALTHY")]
    Unhealthy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "integration_deliveries_status"
)]
pub enum IntegrationDeliveriesStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "DELIVERED")]
    Delivered,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "integration_log_status"
)]
pub enum IntegrationLogStatus {
    #[sea_orm(string_value = "SUCCESS")]
    Success,
    #[sea_orm(string_value = "FAILURE")]
    Failure,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "integration_providers_prov_status"
)]
pub enum IntegrationProvidersProvStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
    #[sea_orm(string_value = "MAINTENANCE")]
    Maintenance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "integration_providers_service_type"
)]
pub enum IntegrationProvidersServiceType {
    #[sea_orm(string_value = "KYC")]
    Kyc,
    #[sea_orm(string_value = "CREDIT_BUREAU")]
    CreditBureau,
    #[sea_orm(string_value = "SMS_GATEWAY")]
    SmsGateway,
    #[sea_orm(string_value = "PAYMENT_PROCESSOR")]
    PaymentProcessor,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "integration_webhook_status"
)]
pub enum IntegrationWebhookStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ledger_lock_type")]
pub enum LedgerLockType {
    #[sea_orm(string_value = "MONTH_END")]
    MonthEnd,
    #[sea_orm(string_value = "YEAR_END")]
    YearEnd,
    #[sea_orm(string_value = "AUDIT")]
    Audit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_application_status"
)]
pub enum LoanApplicationStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
    #[sea_orm(string_value = "DISBURSED")]
    Disbursed,
    #[sea_orm(string_value = "REPAID")]
    Repaid,
    #[sea_orm(string_value = "WRITTEN_OFF")]
    WrittenOff,
    #[sea_orm(string_value = "RESCHEDULED")]
    Rescheduled,
    #[sea_orm(string_value = "REFINANCED")]
    Refinanced,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_collateral_types"
)]
pub enum LoanCollateralTypes {
    #[sea_orm(string_value = "LAND")]
    Land,
    #[sea_orm(string_value = "BUILDING")]
    Building,
    #[sea_orm(string_value = "VEHICLE")]
    Vehicle,
    #[sea_orm(string_value = "EQUIPMENT")]
    Equipment,
    #[sea_orm(string_value = "INVENTORY")]
    Inventory,
    #[sea_orm(string_value = "CASH")]
    Cash,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_penalty_status"
)]
pub enum LoanPenaltyStatus {
    #[sea_orm(string_value = "UNPAID")]
    Unpaid,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "PROCESSING")]
    Processing,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "loan_penalty_type")]
pub enum LoanPenaltyType {
    #[sea_orm(string_value = "LATE_PAYMENT")]
    LatePayment,
    #[sea_orm(string_value = "DEFAULT")]
    Default,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_product_calc_method"
)]
pub enum LoanProductCalcMethod {
    #[sea_orm(string_value = "FLAT")]
    Flat,
    #[sea_orm(string_value = "REDUCING_BALANCE")]
    ReducingBalance,
    #[sea_orm(string_value = "DECLINING_BALANCE")]
    DecliningBalance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "loan_product_freq")]
pub enum LoanProductFreq {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "BULLET")]
    Bullet,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_product_interest_type"
)]
pub enum LoanProductInterestType {
    #[sea_orm(string_value = "FIXED")]
    Fixed,
    #[sea_orm(string_value = "VARIABLE")]
    Variable,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_repayment_freq"
)]
pub enum LoanRepaymentFreq {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "BULLET")]
    Bullet,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_repayment_methods"
)]
pub enum LoanRepaymentMethods {
    #[sea_orm(string_value = "MOBILE_MONEY")]
    MobileMoney,
    #[sea_orm(string_value = "BANK_TRANSFER")]
    BankTransfer,
    #[sea_orm(string_value = "CASH")]
    Cash,
    #[sea_orm(string_value = "SALARY_DEDUCTION")]
    SalaryDeduction,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_repayment_schedule_status"
)]
pub enum LoanRepaymentScheduleStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PARTIAL")]
    Partial,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "OVERDUE")]
    Overdue,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_repayment_status"
)]
pub enum LoanRepaymentStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSING")]
    Processing,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "loan_rescheduling_status"
)]
pub enum LoanReschedulingStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "ONGOING")]
    Ongoing,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "loan_risk_rating")]
pub enum LoanRiskRating {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
    #[sea_orm(string_value = "CRITICAL")]
    Critical,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "maintenance_window_status"
)]
pub enum MaintenanceWindowStatus {
    #[sea_orm(string_value = "SCHEDULED")]
    Scheduled,
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "POSTPONED")]
    Postponed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "maker_checker_checker_action"
)]
pub enum MakerCheckerCheckerAction {
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "maker_checker_reference_type"
)]
pub enum MakerCheckerReferenceType {
    #[sea_orm(string_value = "TRANSACTION")]
    Transaction,
    #[sea_orm(string_value = "LOAN_APPROVAL")]
    LoanApproval,
    #[sea_orm(string_value = "PRODUCT_CHANGE")]
    ProductChange,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "maker_checker_status"
)]
pub enum MakerCheckerStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "notification_queue_status"
)]
pub enum NotificationQueueStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "SENT")]
    Sent,
    #[sea_orm(string_value = "DELIVERED")]
    Delivered,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "notification_type")]
pub enum NotificationType {
    #[sea_orm(string_value = "SMS")]
    Sms,
    #[sea_orm(string_value = "EMAIL")]
    Email,
    #[sea_orm(string_value = "PUSH")]
    Push,
    #[sea_orm(string_value = "WHATSAPP")]
    Whatsapp,
    #[sea_orm(string_value = "IN_APP")]
    InApp,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "product_workflows_product_type"
)]
pub enum ProductWorkflowsProductType {
    #[sea_orm(string_value = "LOAN_PRODUCT")]
    LoanProduct,
    #[sea_orm(string_value = "SAVINGS_PRODUCT")]
    SavingsProduct,
    #[sea_orm(string_value = "ACCOUNT_TYPE")]
    AccountType,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "product_workflows_status"
)]
pub enum ProductWorkflowsStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "refund_workflow_approval_status"
)]
pub enum RefundWorkflowApprovalStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "APPROVED")]
    Approved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "refund_workflow_refund_type"
)]
pub enum RefundWorkflowRefundType {
    #[sea_orm(string_value = "FAILED_TRANSACTION")]
    FailedTransaction,
    #[sea_orm(string_value = "FRAUD")]
    Fraud,
    #[sea_orm(string_value = "CUSTOMER_SERVICE")]
    CustomerService,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "regu_reports_report_type"
)]
pub enum ReguReportsReportType {
    #[sea_orm(string_value = "CAPITAL_ADEQUACY")]
    CapitalAdequacy,
    #[sea_orm(string_value = "LIQUIDITY")]
    Liquidity,
    #[sea_orm(string_value = "ASSET_QUALITY")]
    AssetQuality,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "regu_reports_status"
)]
pub enum ReguReportsStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "FINAL")]
    Final,
    #[sea_orm(string_value = "SUBMITTED")]
    Submitted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_category")]
pub enum ReportCategory {
    #[sea_orm(string_value = "PORTFOLIO")]
    Portfolio,
    #[sea_orm(string_value = "PERFORMANCE")]
    Performance,
    #[sea_orm(string_value = "COMPLIANCE")]
    Compliance,
    #[sea_orm(string_value = "RISK")]
    Risk,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_frequency")]
pub enum ReportFrequency {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "ADHOC")]
    Adhoc,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "risk_level_enum")]
pub enum RiskLevelEnum {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "saving_goals_status"
)]
pub enum SavingGoalsStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "PAUSED")]
    Paused,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "ABANDONED")]
    Abandoned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "savings_product_freq"
)]
pub enum SavingsProductFreq {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "savings_product_interest_calc"
)]
pub enum SavingsProductInterestCalc {
    #[sea_orm(string_value = "SIMPLE")]
    Simple,
    #[sea_orm(string_value = "COMPOUND_ANNUAL")]
    CompoundAnnual,
    #[sea_orm(string_value = "COMPOUND_SEMI_ANNUAL")]
    CompoundSemiAnnual,
    #[sea_orm(string_value = "COMPOUND_QUARTERLY")]
    CompoundQuarterly,
    #[sea_orm(string_value = "COMPOUND_MONTHLY")]
    CompoundMonthly,
    #[sea_orm(string_value = "COMPOUND_DAILY")]
    CompoundDaily,
    #[sea_orm(string_value = "CONTINUOUS")]
    Continuous,
    #[sea_orm(string_value = "DAILY_BALANCE")]
    DailyBalance,
    #[sea_orm(string_value = "AVERAGE_DAILY_BALANCE")]
    AverageDailyBalance,
    #[sea_orm(string_value = "MINIMUM_BALANCE")]
    MinimumBalance,
    #[sea_orm(string_value = "TIERED")]
    Tiered,
    #[sea_orm(string_value = "BONUS")]
    Bonus,
    #[sea_orm(string_value = "CONDITIONAL")]
    Conditional,
    #[sea_orm(string_value = "FIXED_SIMPLE")]
    FixedSimple,
    #[sea_orm(string_value = "FIXED_COMPOUND")]
    FixedCompound,
    #[sea_orm(string_value = "FIXED_PAYOUT")]
    FixedPayout,
    #[sea_orm(string_value = "PROFIT_SHARING")]
    ProfitSharing,
    #[sea_orm(string_value = "HYBRID")]
    Hybrid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "savings_product_payout_freq"
)]
pub enum SavingsProductPayoutFreq {
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "QUARTERLY")]
    Quarterly,
    #[sea_orm(string_value = "YEARLY")]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "savings_product_type"
)]
pub enum SavingsProductType {
    #[sea_orm(string_value = "TARGET")]
    Target,
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "ROTATIONAL")]
    Rotational,
    #[sea_orm(string_value = "GROUP")]
    Group,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "sla_config_category"
)]
pub enum SlaConfigCategory {
    #[sea_orm(string_value = "TICKET_RESOLUTION")]
    TicketResolution,
    #[sea_orm(string_value = "LOAN_APPROVAL")]
    LoanApproval,
    #[sea_orm(string_value = "DISPUTE_RESOLUTION")]
    DisputeResolution,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "staff_employment_enum"
)]
pub enum StaffEmploymentEnum {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "staff_gender_enum")]
pub enum StaffGenderEnum {
    #[sea_orm(string_value = "MALE")]
    Male,
    #[sea_orm(string_value = "FEMALE")]
    Female,
    #[sea_orm(string_value = "OTHER")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "staff_task_priority"
)]
pub enum StaffTaskPriority {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
    #[sea_orm(string_value = "CRITICAL")]
    Critical,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "staff_task_status")]
pub enum StaffTaskStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "IN_PROGRESS")]
    InProgress,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "PAUSED")]
    Paused,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "standing_orders_freq"
)]
pub enum StandingOrdersFreq {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
    #[sea_orm(string_value = "QUARTERLY")]
    Quarterly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "statement_status")]
pub enum StatementStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "FINAL")]
    Final,
    #[sea_orm(string_value = "AUDITED")]
    Audited,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "statement_type")]
pub enum StatementType {
    #[sea_orm(string_value = "BALANCE_SHEET")]
    BalanceSheet,
    #[sea_orm(string_value = "PROFIT_LOSS")]
    ProfitLoss,
    #[sea_orm(string_value = "CASH_FLOW")]
    CashFlow,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "super_admin_status")]
pub enum SuperAdminStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "support_tickets_category"
)]
pub enum SupportTicketsCategory {
    #[sea_orm(string_value = "TRANSACTION_ISSUE")]
    TransactionIssue,
    #[sea_orm(string_value = "LOAN_QUERY")]
    LoanQuery,
    #[sea_orm(string_value = "ACCOUNT_QUERY")]
    AccountQuery,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "support_tickets_priority"
)]
pub enum SupportTicketsPriority {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
    #[sea_orm(string_value = "CRITICAL")]
    Critical,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "support_tickets_status"
)]
pub enum SupportTicketsStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "IN_PROGRESS")]
    InProgress,
    #[sea_orm(string_value = "WAITING_CUSTOMER")]
    WaitingCustomer,
    #[sea_orm(string_value = "RESOLVED")]
    Resolved,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "tax_withholding_type"
)]
pub enum TaxWithholdingType {
    #[sea_orm(string_value = "VAT")]
    Vat,
    #[sea_orm(string_value = "WITHHOLDING_TAX")]
    WithholdingTax,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "teller_cash_drawers_status"
)]
pub enum TellerCashDrawersStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "BALANCED")]
    Balanced,
    #[sea_orm(string_value = "VARIANCE")]
    Variance,
    #[sea_orm(string_value = "FORCE_CLOSED")]
    ForceClosed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "teller_recon_type")]
pub enum TellerReconType {
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "FORCE_CLOSE")]
    ForceClose,
    #[sea_orm(string_value = "EMERGENCY")]
    Emergency,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "teller_status")]
pub enum TellerStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "ticket_interaction_created_type"
)]
pub enum TicketInteractionCreatedType {
    #[sea_orm(string_value = "CUSTOMER")]
    Customer,
    #[sea_orm(string_value = "STAFF")]
    Staff,
    #[sea_orm(string_value = "SYSTEM")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "ticket_interaction_type"
)]
pub enum TicketInteractionType {
    #[sea_orm(string_value = "CUSTOMER_MESSAGE")]
    CustomerMessage,
    #[sea_orm(string_value = "STAFF_RESPONSE")]
    StaffResponse,
    #[sea_orm(string_value = "INTERNAL_NOTE")]
    InternalNote,
    #[sea_orm(string_value = "SYSTEM_ACTION")]
    SystemAction,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_category_type"
)]
pub enum TransactionCategoryType {
    #[sea_orm(string_value = "CASH_DEPOSIT")]
    CashDeposit,
    #[sea_orm(string_value = "CASH_WITHDRAWAL")]
    CashWithdrawal,
    #[sea_orm(string_value = "TRANSFER")]
    Transfer,
    #[sea_orm(string_value = "LOAN_DISBURSEMENT")]
    LoanDisbursement,
    #[sea_orm(string_value = "LOAN_REPAYMENT")]
    LoanRepayment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_dispute_status"
)]
pub enum TransactionDisputeStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "INVESTIGATION")]
    Investigation,
    #[sea_orm(string_value = "RESOLVED")]
    Resolved,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_dispute_type"
)]
pub enum TransactionDisputeType {
    #[sea_orm(string_value = "UNAUTHORIZED")]
    Unauthorized,
    #[sea_orm(string_value = "DUPLICATE")]
    Duplicate,
    #[sea_orm(string_value = "INCORRECT_AMOUNT")]
    IncorrectAmount,
    #[sea_orm(string_value = "NOT_RECEIVED")]
    NotReceived,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_limits_limit_type"
)]
pub enum TransactionLimitsLimitType {
    #[sea_orm(string_value = "PER_TRANSACTION")]
    PerTransaction,
    #[sea_orm(string_value = "DAILY")]
    Daily,
    #[sea_orm(string_value = "WEEKLY")]
    Weekly,
    #[sea_orm(string_value = "MONTHLY")]
    Monthly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_priority"
)]
pub enum TransactionPriority {
    #[sea_orm(string_value = "LOW")]
    Low,
    #[sea_orm(string_value = "MEDIUM")]
    Medium,
    #[sea_orm(string_value = "HIGH")]
    High,
    #[sea_orm(string_value = "CRITICAL")]
    Critical,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_reversal_status"
)]
pub enum TransactionReversalStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_reversal_typs"
)]
pub enum TransactionReversalTyps {
    #[sea_orm(string_value = "CUSTOMER_REQUEST")]
    CustomerRequest,
    #[sea_orm(string_value = "FRAUD")]
    Fraud,
    #[sea_orm(string_value = "ERROR")]
    Error,
    #[sea_orm(string_value = "COMPLIANCE")]
    Compliance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_status")]
pub enum TransactionStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "REVERSED")]
    Reversed,
    #[sea_orm(string_value = "DISPUTED")]
    Disputed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_suspicion_type"
)]
pub enum TransactionSuspicionType {
    #[sea_orm(string_value = "MONEY_LAUNDERING")]
    MoneyLaundering,
    #[sea_orm(string_value = "TERRORIST_FINANCING")]
    TerroristFinancing,
    #[sea_orm(string_value = "FRAUD")]
    Fraud,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_suspicions_status"
)]
pub enum TransactionSuspicionsStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "SUBMITTED")]
    Submitted,
    #[sea_orm(string_value = "ACKNOWLEDGED")]
    Acknowledged,
    #[sea_orm(string_value = "UNDER_REVIEW")]
    UnderReview,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_type")]
pub enum TransactionType {
    #[sea_orm(string_value = "DEBIT")]
    Debit,
    #[sea_orm(string_value = "CREDIT")]
    Credit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "vault_status")]
pub enum VaultStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "verification_status_type"
)]
pub enum VerificationStatusType {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "VERIFIED")]
    Verified,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wallet_prov_status")]
pub enum WalletProvStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "wallet_reconciliation_status"
)]
pub enum WalletReconciliationStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "MATCHED")]
    Matched,
    #[sea_orm(string_value = "UNMATCHED")]
    Unmatched,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "wallet_trans_direction"
)]
pub enum WalletTransDirection {
    #[sea_orm(string_value = "IN")]
    In,
    #[sea_orm(string_value = "OUT")]
    Out,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "wallet_trans_status"
)]
pub enum WalletTransStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSING")]
    Processing,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wallet_trans_type")]
pub enum WalletTransType {
    #[sea_orm(string_value = "TOPUP")]
    Topup,
    #[sea_orm(string_value = "WITHDRAWAL")]
    Withdrawal,
    #[sea_orm(string_value = "P2P")]
    P2p,
    #[sea_orm(string_value = "MERCHANT_PAYMENT")]
    MerchantPayment,
    #[sea_orm(string_value = "BANK_TRANSFER")]
    BankTransfer,
}
