//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SlaConfigCategory;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sla_configurations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub sla_name: String,
    pub sla_category: SlaConfigCategory,
    pub target_resolution_time_minutes: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub priority_levels: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub applies_to_groups: Option<Json>,
    pub escalation_enabled: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub escalation_rules: Option<Json>,
    pub is_active: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
