//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::StaffEmploymentEnum;
use super::sea_orm_active_enums::StaffGenderEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub branch_id: Option<i64>,
    #[sea_orm(unique)]
    pub employee_number: String,
    pub first_name: String,
    pub last_name: String,
    pub full_name: Option<String>,
    pub phone_country_code: Option<String>,
    #[sea_orm(unique)]
    pub phone_number: String,
    #[sea_orm(unique)]
    pub email_address: String,
    pub date_of_birth: Option<Date>,
    pub gender: Option<StaffGenderEnum>,
    pub nationality: Option<String>,
    pub job_title: Option<String>,
    pub department: Option<String>,
    pub employment_status: Option<StaffEmploymentEnum>,
    pub date_hired: Option<Date>,
    pub date_terminated: Option<Date>,
    pub termination_reason: Option<String>,
    pub role_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub permissions: Option<Json>,
    pub password_hash: String,
    pub password_last_changed_at: Option<DateTimeWithTimeZone>,
    pub is_mfa_enabled: Option<bool>,
    pub mfa_secret_encrypted: Option<String>,
    pub failed_login_attempts: Option<i32>,
    pub locked_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub performance_rating: Option<Decimal>,
    pub last_appraisal_date: Option<Date>,
    pub supervisor_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_links::Entity")]
    AccountLinks,
    #[sea_orm(has_many = "super::accruals_and_provisions::Entity")]
    AccrualsAndProvisions,
    #[sea_orm(has_many = "super::agent_commission_rules::Entity")]
    AgentCommissionRules,
    #[sea_orm(has_many = "super::agent_kyc_docs::Entity")]
    AgentKycDocs,
    #[sea_orm(has_many = "super::agent_settlements::Entity")]
    AgentSettlements,
    #[sea_orm(has_many = "super::agents::Entity")]
    Agents,
    #[sea_orm(has_many = "super::aml_rules::Entity")]
    AmlRules,
    #[sea_orm(
        belongs_to = "super::branches::Entity",
        from = "Column::BranchId",
        to = "super::branches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Branches,
    #[sea_orm(has_many = "super::commission_payouts::Entity")]
    CommissionPayouts,
    #[sea_orm(has_many = "super::currency_transaction_reports::Entity")]
    CurrencyTransactionReports,
    #[sea_orm(has_many = "super::customer_address_verifications::Entity")]
    CustomerAddressVerifications,
    #[sea_orm(has_many = "super::customer_education_content::Entity")]
    CustomerEducationContent,
    #[sea_orm(has_many = "super::customer_identifications::Entity")]
    CustomerIdentifications,
    #[sea_orm(has_many = "super::data_backups::Entity")]
    DataBackups,
    #[sea_orm(has_many = "super::data_retention_rules::Entity")]
    DataRetentionRules,
    #[sea_orm(has_many = "super::fee_types::Entity")]
    FeeTypes,
    #[sea_orm(has_many = "super::field_officer_routes::Entity")]
    FieldOfficerRoutes,
    #[sea_orm(has_many = "super::generated_reports::Entity")]
    GeneratedReports,
    #[sea_orm(has_many = "super::gl_daily_balances::Entity")]
    GlDailyBalances,
    #[sea_orm(has_many = "super::gl_postings::Entity")]
    GlPostings,
    #[sea_orm(has_many = "super::gl_reversals::Entity")]
    GlReversals,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::integration_api_keys::Entity")]
    IntegrationApiKeys,
    #[sea_orm(has_many = "super::integration_providers::Entity")]
    IntegrationProviders,
    #[sea_orm(has_many = "super::integration_webhooks::Entity")]
    IntegrationWebhooks,
    #[sea_orm(has_many = "super::loan_application_status_history::Entity")]
    LoanApplicationStatusHistory,
    #[sea_orm(has_many = "super::loan_collaterals::Entity")]
    LoanCollaterals,
    #[sea_orm(has_many = "super::loan_penalties::Entity")]
    LoanPenalties,
    #[sea_orm(has_many = "super::loan_products::Entity")]
    LoanProducts,
    #[sea_orm(has_many = "super::loan_provisioning::Entity")]
    LoanProvisioning,
    #[sea_orm(has_many = "super::loan_rescheduling::Entity")]
    LoanRescheduling,
    #[sea_orm(has_many = "super::loan_write_offs::Entity")]
    LoanWriteOffs,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(has_many = "super::notification_queue::Entity")]
    NotificationQueue,
    #[sea_orm(has_many = "super::notification_templates::Entity")]
    NotificationTemplates,
    #[sea_orm(has_many = "super::product_visibility_rules::Entity")]
    ProductVisibilityRules,
    #[sea_orm(has_many = "super::report_schedules::Entity")]
    ReportSchedules,
    #[sea_orm(has_many = "super::savings_products::Entity")]
    SavingsProducts,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::SupervisorId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::staff_commissions::Entity")]
    StaffCommissions,
    #[sea_orm(has_many = "super::staff_roles::Entity")]
    StaffRoles,
    #[sea_orm(has_many = "super::standing_orders::Entity")]
    StandingOrders,
    #[sea_orm(has_many = "super::suspicious_transaction_reports::Entity")]
    SuspiciousTransactionReports,
    #[sea_orm(has_many = "super::system_maintenance_windows::Entity")]
    SystemMaintenanceWindows,
    #[sea_orm(has_many = "super::teller_cash_drawers::Entity")]
    TellerCashDrawers,
    #[sea_orm(has_many = "super::teller_reconciliations::Entity")]
    TellerReconciliations,
    #[sea_orm(has_many = "super::tellers::Entity")]
    Tellers,
    #[sea_orm(has_many = "super::wallet_reconciliations::Entity")]
    WalletReconciliations,
}

impl Related<super::account_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountLinks.def()
    }
}

impl Related<super::accruals_and_provisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccrualsAndProvisions.def()
    }
}

impl Related<super::agent_commission_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissionRules.def()
    }
}

impl Related<super::agent_kyc_docs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentKycDocs.def()
    }
}

impl Related<super::agent_settlements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentSettlements.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::aml_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlRules.def()
    }
}

impl Related<super::branches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branches.def()
    }
}

impl Related<super::commission_payouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionPayouts.def()
    }
}

impl Related<super::currency_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrencyTransactionReports.def()
    }
}

impl Related<super::customer_address_verifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAddressVerifications.def()
    }
}

impl Related<super::customer_education_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerEducationContent.def()
    }
}

impl Related<super::customer_identifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerIdentifications.def()
    }
}

impl Related<super::data_backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataBackups.def()
    }
}

impl Related<super::data_retention_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataRetentionRules.def()
    }
}

impl Related<super::fee_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeeTypes.def()
    }
}

impl Related<super::field_officer_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FieldOfficerRoutes.def()
    }
}

impl Related<super::generated_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedReports.def()
    }
}

impl Related<super::gl_daily_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlDailyBalances.def()
    }
}

impl Related<super::gl_postings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlPostings.def()
    }
}

impl Related<super::gl_reversals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlReversals.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::integration_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationApiKeys.def()
    }
}

impl Related<super::integration_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationProviders.def()
    }
}

impl Related<super::integration_webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationWebhooks.def()
    }
}

impl Related<super::loan_application_status_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplicationStatusHistory.def()
    }
}

impl Related<super::loan_collaterals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanCollaterals.def()
    }
}

impl Related<super::loan_penalties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanPenalties.def()
    }
}

impl Related<super::loan_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProducts.def()
    }
}

impl Related<super::loan_provisioning::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProvisioning.def()
    }
}

impl Related<super::loan_rescheduling::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRescheduling.def()
    }
}

impl Related<super::loan_write_offs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanWriteOffs.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::notification_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationQueue.def()
    }
}

impl Related<super::notification_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTemplates.def()
    }
}

impl Related<super::product_visibility_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVisibilityRules.def()
    }
}

impl Related<super::report_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportSchedules.def()
    }
}

impl Related<super::savings_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsProducts.def()
    }
}

impl Related<super::staff_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffCommissions.def()
    }
}

impl Related<super::staff_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffRoles.def()
    }
}

impl Related<super::standing_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StandingOrders.def()
    }
}

impl Related<super::suspicious_transaction_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuspiciousTransactionReports.def()
    }
}

impl Related<super::system_maintenance_windows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemMaintenanceWindows.def()
    }
}

impl Related<super::teller_cash_drawers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TellerCashDrawers.def()
    }
}

impl Related<super::teller_reconciliations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TellerReconciliations.def()
    }
}

impl Related<super::tellers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tellers.def()
    }
}

impl Related<super::wallet_reconciliations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletReconciliations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
