//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AgentCommissionsStatus;
use super::sea_orm_active_enums::AgentCommissionsTransType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff_commissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub staff_id: i64,
    pub commission_rule_id: i64,
    pub transaction_id: Option<i64>,
    pub transaction_reference: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub transaction_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub commission_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub commission_amount: Decimal,
    pub transaction_type: AgentCommissionsTransType,
    pub status: AgentCommissionsStatus,
    pub paid_at: Option<DateTimeWithTimeZone>,
    pub payroll_cycle: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agent_commission_rules::Entity",
        from = "Column::CommissionRuleId",
        to = "super::agent_commission_rules::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AgentCommissionRules,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::agent_commission_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissionRules.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
