//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::StaffTaskPriority;
use super::sea_orm_active_enums::StaffTaskStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub task_name: String,
    pub task_description: Option<String>,
    pub assigned_to: i64,
    pub assigned_by: i64,
    pub customer_id: Option<i64>,
    pub loan_application_id: Option<i64>,
    pub account_id: Option<i64>,
    pub due_date: Option<DateTimeWithTimeZone>,
    pub priority: Option<StaffTaskPriority>,
    pub status: Option<StaffTaskStatus>,
    pub completion_percentage: Option<i32>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub completed_notes: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::loan_applications::Entity",
        from = "Column::LoanApplicationId",
        to = "super::loan_applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LoanApplications,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedTo",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanApplications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
