//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccTypeStatus;
use super::sea_orm_active_enums::StandingOrdersFreq;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "standing_orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub debit_account_id: i64,
    pub credit_account_id: Option<i64>,
    pub beneficiary_name: Option<String>,
    pub beneficiary_account: Option<String>,
    pub beneficiary_bank_code: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    pub frequency: Option<StandingOrdersFreq>,
    pub day_of_week: Option<i32>,
    pub day_of_month: Option<i32>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub next_run_date: Option<Date>,
    pub narration: Option<String>,
    pub status: Option<AccTypeStatus>,
    pub failure_count: Option<i32>,
    pub max_failure_count: Option<i32>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
