//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SuperAdminStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "super_admins")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email_address: String,
    pub password_hash: String,
    pub mfa_enabled: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mfa_secret_encrypted: Option<String>,
    pub full_name: Option<String>,
    pub phone_number: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Json,
    pub admin_status: Option<SuperAdminStatus>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::admin_audit_logs::Entity")]
    AdminAuditLogs,
}

impl Related<super::admin_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminAuditLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
