//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SupportTicketsCategory;
use super::sea_orm_active_enums::SupportTicketsPriority;
use super::sea_orm_active_enums::SupportTicketsStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "support_tickets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    #[sea_orm(unique)]
    pub ticket_number: String,
    pub ticket_subject: String,
    #[sea_orm(column_type = "Text")]
    pub ticket_description: String,
    pub ticket_category: Option<SupportTicketsCategory>,
    pub ticket_subcategory: Option<String>,
    pub priority: Option<SupportTicketsPriority>,
    pub assigned_to: Option<i64>,
    pub assigned_group: Option<String>,
    pub status: Option<SupportTicketsStatus>,
    pub is_escalated: Option<bool>,
    pub escalation_level: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution_summary: Option<String>,
    pub resolution_time_minutes: Option<i32>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub resolved_by: Option<i64>,
    pub customer_rating: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub customer_feedback: Option<String>,
    pub sla_breach: Option<bool>,
    pub sla_deadline: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedTo",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ResolvedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff1,
    #[sea_orm(has_many = "super::ticket_interactions::Entity")]
    TicketInteractions,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::ticket_interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketInteractions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
