//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::MaintenanceWindowStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_maintenance_windows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub window_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub window_description: Option<String>,
    pub scheduled_start_at: DateTimeWithTimeZone,
    pub scheduled_end_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub affected_services: Option<Json>,
    pub notification_sent: Option<bool>,
    pub window_status: Option<MaintenanceWindowStatus>,
    pub actual_start_at: Option<DateTimeWithTimeZone>,
    pub actual_end_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Staff,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
