//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::HealthStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_health_metrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub metric_name: String,
    pub metric_category: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub metric_value: Option<Decimal>,
    pub metric_unit: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub warning_threshold: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub critical_threshold: Option<Decimal>,
    pub metric_status: Option<HealthStatus>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub recorded_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
