//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TellerCashDrawersStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "teller_cash_drawers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub teller_id: i64,
    pub opening_cash_amount: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub opening_cash: Option<Json>,
    pub total_cash_in: Option<i64>,
    pub total_cash_out: Option<i64>,
    pub cheque_count: Option<i32>,
    pub total_cheque_amount: Option<i64>,
    pub transfer_in_count: Option<i32>,
    pub total_transfer_in_amount: Option<i64>,
    pub transfer_out_count: Option<i32>,
    pub total_transfer_out_amount: Option<i64>,
    pub closing_balance: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub closing_cash: Option<Json>,
    pub expected_amount: Option<i64>,
    pub variance_amount: Option<i64>,
    pub variance_reason: Option<String>,
    pub status: Option<TellerCashDrawersStatus>,
    pub opened_at: Option<DateTimeWithTimeZone>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub closed_by_supervisor: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ClosedBySupervisor",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(has_many = "super::teller_reconciliations::Entity")]
    TellerReconciliations,
    #[sea_orm(
        belongs_to = "super::tellers::Entity",
        from = "Column::TellerId",
        to = "super::tellers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tellers,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::teller_reconciliations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TellerReconciliations.def()
    }
}

impl Related<super::tellers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tellers.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
