//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TellerCashDrawersStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teller_cash_drawers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub teller_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub opening_balance: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub opening_cash: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_cash_in: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_cash_out: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_cheques: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_transfers_in: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_transfers_out: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub closing_balance: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub closing_cash: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub expected_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub variance_amount: Option<Decimal>,
    pub variance_reason: Option<String>,
    pub status: Option<TellerCashDrawersStatus>,
    pub opened_at: Option<DateTimeWithTimeZone>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub closed_by_supervisor: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ClosedBySupervisor",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(has_many = "super::teller_reconciliations::Entity")]
    TellerReconciliations,
    #[sea_orm(
        belongs_to = "super::tellers::Entity",
        from = "Column::TellerId",
        to = "super::tellers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tellers,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::teller_reconciliations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TellerReconciliations.def()
    }
}

impl Related<super::tellers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tellers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
