//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TellerReconType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teller_reconciliations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub cash_drawer_id: i64,
    pub reconciliation_type: Option<TellerReconType>,
    pub notes: Option<String>,
    pub supervisor_id: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::SupervisorId",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
    #[sea_orm(
        belongs_to = "super::teller_cash_drawers::Entity",
        from = "Column::CashDrawerId",
        to = "super::teller_cash_drawers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TellerCashDrawers,
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::teller_cash_drawers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TellerCashDrawers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
