//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TicketInteractionCreatedType;
use super::sea_orm_active_enums::TicketInteractionType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ticket_interactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub ticket_id: i64,
    pub interaction_type: TicketInteractionType,
    #[sea_orm(column_type = "Text")]
    pub interaction_content: String,
    pub created_by: Option<i64>,
    pub created_by_type: Option<TicketInteractionCreatedType>,
    pub is_internal: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attachments: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::support_tickets::Entity",
        from = "Column::TicketId",
        to = "super::support_tickets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SupportTickets,
}

impl Related<super::support_tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SupportTickets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
