//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TransactionCategoryType;
use super::sea_orm_active_enums::TransactionStatus;
use super::sea_orm_active_enums::TransactionType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_channel_id: i64,
    pub transaction_reference: Option<String>,
    pub parent_transaction_id: i64,
    pub reversal_reason: Option<String>,
    pub debit_account_id: Option<i64>,
    pub credit_account_id: Option<i64>,
    pub debit_customer_id: Option<i64>,
    pub credit_customer_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub fee_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub vat_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub total_amount: Option<Decimal>,
    pub transaction_type: Option<TransactionType>,
    pub transaction_category: Option<TransactionCategoryType>,
    pub description: Option<String>,
    pub narrative: Option<String>,
    pub external_reference: Option<String>,
    pub status: Option<TransactionStatus>,
    pub posted_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub failed_at: Option<DateTimeWithTimeZone>,
    pub failure_reason: Option<String>,
    pub value_date: Option<Date>,
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub device_id: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub location: Option<Json>,
    pub is_suspicious: Option<bool>,
    pub aml_alert_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub approved_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::CreditAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::DebitAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts1,
    #[sea_orm(has_many = "super::agent_commissions::Entity")]
    AgentCommissions,
    #[sea_orm(has_many = "super::agent_transactions::Entity")]
    AgentTransactions,
    #[sea_orm(has_many = "super::aml_alerts::Entity")]
    AmlAlerts,
    #[sea_orm(has_many = "super::chargebacks::Entity")]
    Chargebacks,
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CreditCustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers2,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::DebitCustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers1,
    #[sea_orm(has_many = "super::gl_postings::Entity")]
    GlPostings,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::loan_repayments::Entity")]
    LoanRepayments,
    #[sea_orm(has_many = "super::refund_workflows::Entity")]
    RefundWorkflows,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::CreatedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(has_many = "super::staff_commissions::Entity")]
    StaffCommissions,
    #[sea_orm(has_many = "super::tax_withholding::Entity")]
    TaxWithholding,
    #[sea_orm(
        belongs_to = "super::transaction_channels::Entity",
        from = "Column::TransactionChannelId",
        to = "super::transaction_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TransactionChannels,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentTransactionId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::wallet_transactions::Entity")]
    WalletTransactions,
}

impl Related<super::agent_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentCommissions.def()
    }
}

impl Related<super::agent_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentTransactions.def()
    }
}

impl Related<super::aml_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AmlAlerts.def()
    }
}

impl Related<super::chargebacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chargebacks.def()
    }
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::gl_postings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlPostings.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::loan_repayments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanRepayments.def()
    }
}

impl Related<super::refund_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundWorkflows.def()
    }
}

impl Related<super::staff_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffCommissions.def()
    }
}

impl Related<super::tax_withholding::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxWithholding.def()
    }
}

impl Related<super::transaction_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionChannels.def()
    }
}

impl Related<super::wallet_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
