//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TransactionDisputeStatus;
use super::sea_orm_active_enums::TransactionDisputeType;
use super::sea_orm_active_enums::TransactionPriority;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction_disputes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_id: i64,
    pub customer_id: i64,
    pub dispute_type: Option<TransactionDisputeType>,
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub amount_disputed: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub supporting_documents: Option<Json>,
    pub status: Option<TransactionDisputeStatus>,
    pub priority: Option<TransactionPriority>,
    pub resolution: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub refund_amount: Option<Decimal>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub sla_deadline: Option<DateTimeWithTimeZone>,
    pub assigned_to: Option<i64>,
    pub resolved_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedTo",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ResolvedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
}

impl ActiveModelBehavior for ActiveModel {}
