//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TransactionReversalStatus;
use super::sea_orm_active_enums::TransactionReversalTyps;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction_reversals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub orginal_transaction_id: i64,
    pub reversal_transaction_id: Option<i64>,
    pub institution_id: i64,
    pub reversal_type: Option<TransactionReversalTyps>,
    pub reason: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub amount: Option<Decimal>,
    pub status: Option<TransactionReversalStatus>,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub maker_checker_workflow_id: Option<i64>,
    pub requested_by: Option<i64>,
    pub approved_by: Option<i64>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ApprovedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff2,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::RequestedBy",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff1,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::OrginalTransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions2,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::ReversalTransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions1,
}

impl ActiveModelBehavior for ActiveModel {}
