//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::CustomerType;
use super::sea_orm_active_enums::TransactionLimitsLimitType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub transaction_channel_id: i64,
    pub customer_type: Option<CustomerType>,
    pub account_category_id: i64,
    pub limit_type: Option<TransactionLimitsLimitType>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub max_amount: Option<Decimal>,
    pub max_count: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    pub is_active: Option<bool>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub kyc_tier: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_categories::Entity",
        from = "Column::AccountCategoryId",
        to = "super::account_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccountCategories,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::transaction_channels::Entity",
        from = "Column::TransactionChannelId",
        to = "super::transaction_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TransactionChannels,
}

impl Related<super::account_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountCategories.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transaction_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
