//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::WalletProvStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wallets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub customer_id: i64,
    pub wallet_provider_id: i64,
    #[sea_orm(unique)]
    pub wallet_number: String,
    pub wallet_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub currency: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub available_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub ledger_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub hold_balance: Option<Decimal>,
    pub status: Option<WalletProvStatus>,
    pub is_primary: Option<bool>,
    pub provider_customer_id: Option<String>,
    pub provider_wallet_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub provider_metadata: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(has_many = "super::refund_workflows::Entity")]
    RefundWorkflows,
    #[sea_orm(
        belongs_to = "super::wallet_providers::Entity",
        from = "Column::WalletProviderId",
        to = "super::wallet_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WalletProviders,
    #[sea_orm(has_many = "super::wallet_transactions::Entity")]
    WalletTransactions,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::refund_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundWorkflows.def()
    }
}

impl Related<super::wallet_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletProviders.def()
    }
}

impl Related<super::wallet_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
