//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::WalletTransDirection;
use super::sea_orm_active_enums::WalletTransStatus;
use super::sea_orm_active_enums::WalletTransType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wallet_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub institution_id: i64,
    pub wallet_id: i64,
    #[sea_orm(unique)]
    pub transaction_reference: String,
    #[sea_orm(unique)]
    pub external_reference: String,
    pub transaction_direction: WalletTransDirection,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub fee_amount: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary")]
    pub currency: Json,
    pub counter_party_phone: Option<String>,
    pub counter_party_name: Option<String>,
    pub counter_party_wallet_id: Option<String>,
    pub transaction_type: Option<WalletTransType>,
    pub status: Option<WalletTransStatus>,
    pub posted_at: Option<DateTimeWithTimeZone>,
    pub bank_transaction_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub provider_response: Option<Json>,
    pub provider_status_code: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institutions::Entity",
        from = "Column::InstitutionId",
        to = "super::institutions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Institutions,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::BankTransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::WalletId",
        to = "super::wallets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wallets,
}

impl Related<super::institutions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institutions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
