//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IntegrationDeliveriesStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "webhook_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub webhook_id: i64,
    pub event_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub event_data: Json,
    pub delivery_attempt: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request_payload: Option<Json>,
    pub http_status_code: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_body: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response_headers: Option<Json>,
    pub delivery_status: Option<IntegrationDeliveriesStatus>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::integration_webhooks::Entity",
        from = "Column::WebhookId",
        to = "super::integration_webhooks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IntegrationWebhooks,
}

impl Related<super::integration_webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationWebhooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
